"""
Type stubs for PySide6.QtCore
Generated for modorganizer-linux project
"""

from typing import Any, Callable, Optional, List, Dict, Tuple, Union, TypeVar, Generic
from enum import Enum

T = TypeVar('T')

class QObject:
    def __init__(self, parent: Optional['QObject'] = None) -> None: ...
    def parent(self) -> Optional['QObject']: ...
    def setParent(self, parent: 'QObject') -> None: ...
    def deleteLater(self) -> None: ...
    def children(self) -> List['QObject']: ...
    def findChild(self, type: type, name: str = "") -> Optional['QObject']: ...
    def findChildren(self, type: type, name: str = "") -> List['QObject']: ...
    def setObjectName(self, name: str) -> None: ...
    def objectName(self) -> str: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def blockSignals(self, block: bool) -> bool: ...
    def moveToThread(self, thread: 'QThread') -> None: ...
    def thread(self) -> 'QThread': ...

class QCoreApplication(QObject):
    @staticmethod
    def instance() -> Optional['QCoreApplication']: ...
    @staticmethod
    def exec() -> int: ...
    @staticmethod
    def exit(returnCode: int = 0) -> None: ...
    @staticmethod
    def quit() -> None: ...
    @staticmethod
    def applicationName() -> str: ...
    @staticmethod
    def setApplicationName(name: str) -> None: ...
    @staticmethod
    def applicationVersion() -> str: ...
    @staticmethod
    def setApplicationVersion(version: str) -> None: ...
    @staticmethod
    def organizationName() -> str: ...
    @staticmethod
    def setOrganizationName(name: str) -> None: ...
    @staticmethod
    def organizationDomain() -> str: ...
    @staticmethod
    def setOrganizationDomain(domain: str) -> None: ...
    @staticmethod
    def arguments() -> List[str]: ...
    @staticmethod
    def applicationDirPath() -> str: ...
    @staticmethod
    def applicationFilePath() -> str: ...
    @staticmethod
    def installTranslator(translator: 'QTranslator') -> bool: ...
    @staticmethod
    def removeTranslator(translator: 'QTranslator') -> bool: ...
    @staticmethod
    def translate(context: str, sourceText: str, disambiguation: str = ..., n: int = ...) -> str: ...

class Qt:
    class AlignmentFlag:
        AlignLeft: int = ...
        AlignRight: int = ...
        AlignHCenter: int = ...
        AlignJustify: int = ...
        AlignTop: int = ...
        AlignBottom: int = ...
        AlignVCenter: int = ...
        AlignCenter: int = ...
        AlignAbsolute: int = ...

    class TextFlag:
        TextSingleLine: int = ...
        TextDontClip: int = ...
        TextExpandTabs: int = ...
        TextShowMnemonic: int = ...
        TextWordWrap: int = ...
        TextWrapAnywhere: int = ...
        TextHideMnemonic: int = ...
        TextDontPrint: int = ...
        TextIncludeTrailingSpaces: int = ...
        TextJustificationForced: int = ...

    class TextFormat:
        PlainText: int = ...
        RichText: int = ...
        AutoText: int = ...
        MarkdownText: int = ...

    class TextInteractionFlag:
        NoTextInteraction: int = ...
        TextSelectableByMouse: int = ...
        TextSelectableByKeyboard: int = ...
        LinksAccessibleByMouse: int = ...
        LinksAccessibleByKeyboard: int = ...
        TextEditable: int = ...
        TextEditorInteraction: int = ...
        TextBrowserInteraction: int = ...

    class ItemFlag:
        NoItemFlags: int = ...
        ItemIsSelectable: int = ...
        ItemIsEditable: int = ...
        ItemIsDragEnabled: int = ...
        ItemIsDropEnabled: int = ...
        ItemIsUserCheckable: int = ...
        ItemIsEnabled: int = ...
        ItemIsAutoTristate: int = ...
        ItemNeverHasChildren: int = ...
        ItemIsUserTristate: int = ...

    class CheckState:
        Unchecked: int = ...
        PartiallyChecked: int = ...
        Checked: int = ...

    class Orientation:
        Horizontal: int = ...
        Vertical: int = ...

    class ToolBarArea:
        LeftToolBarArea: int = ...
        RightToolBarArea: int = ...
        TopToolBarArea: int = ...
        BottomToolBarArea: int = ...
        AllToolBarAreas: int = ...
        NoToolBarArea: int = ...

    class DockWidgetArea:
        LeftDockWidgetArea: int = ...
        RightDockWidgetArea: int = ...
        TopDockWidgetArea: int = ...
        BottomDockWidgetArea: int = ...
        AllDockWidgetAreas: int = ...
        NoDockWidgetArea: int = ...

    class ScrollBarPolicy:
       ScrollBarAsNeeded: int = ...
        ScrollBarAlwaysOff: int = ...
        ScrollBarAlwaysOn: int = ...

    class ToolButtonStyle:
        ToolButtonIconOnly: int = ...
        ToolButtonTextOnly: int = ...
        ToolButtonTextBesideIcon: int = ...
        ToolButtonTextUnderIcon: int = ...
        ToolButtonFollowStyle: int = ...

    class CaseSensitivity:
        CaseInsensitive: int = ...
        CaseSensitive: int = ...

    class SortOrder:
        AscendingOrder: int = ...
        DescendingOrder: int = ...

    class DayOfWeek:
        Monday: int = ...
        Tuesday: int = ...
        Wednesday: int = ...
        Thursday: int = ...
        Friday: int = ...
        Saturday: int = ...
        Sunday: int = ...

    class Month:
        January: int = ...
        February: int = ...
        March: int = ...
        April: int = ...
        May: int = ...
        June: int = ...
        July: int = ...
        August: int = ...
        September: int = ...
        October: int = ...
        November: int = ...
        December: int = ...

    class KeyboardModifier:
        NoModifier: int = ...
        ShiftModifier: int = ...
        ControlModifier: int = ...
        AltModifier: int = ...
        MetaModifier: int = ...
        KeypadModifier: int = ...
        GroupSwitchModifier: int = ...

    class Key:
        Key_unknown: int = ...
        Key_Escape: int = ...
        Key_Tab: int = ...
        Key_Backtab: int = ...
        Key_Backspace: int = ...
        Key_Return: int = ...
        Key_Enter: int = ...
        Key_Insert: int = ...
        Key_Delete: int = ...
        Key_Pause: int = ...
        Key_Print: int = ...
        Key_SysReq: int = ...
        Key_Clear: int = ...
        Key_Home: int = ...
        Key_End: int = ...
        Key_Left: int = ...
        Key_Up: int = ...
        Key_Right: int = ...
        Key_Down: int = ...
        Key_PageUp: int = ...
        Key_PageDown: int = ...
        Key_Shift: int = ...
        Key_Control: int = ...
        Key_Meta: int = ...
        Key_Alt: int = ...
        Key_CapsLock: int = ...
        Key_NumLock: int = ...
        Key_ScrollLock: int = ...
        Key_F1: int = ...
        Key_F2: int = ...
        Key_F3: int = ...
        Key_F4: int = ...
        Key_F5: int = ...
        Key_F6: int = ...
        Key_F7: int = ...
        Key_F8: int = ...
        Key_F9: int = ...
        Key_F10: int = ...
        Key_F11: int = ...
        Key_F12: int = ...
        Key_Space: int = ...
        Key_Exclam: int = ...
        Key_QuoteDbl: int = ...
        Key_NumberSign: int = ...
        Key_Dollar: int = ...
        Key_Percent: int = ...
        Key_Ampersand: int = ...
        Key_Apostrophe: int = ...
        Key_ParenLeft: int = ...
        Key_ParenRight: int = ...
        Key_Asterisk: int = ...
        Key_Plus: int = ...
        Key_Comma: int = ...
        Key_Minus: int = ...
        Key_Period: int = ...
        Key_Slash: int = ...
        Key_0: int = ...
        Key_1: int = ...
        Key_2: int = ...
        Key_3: int = ...
        Key_4: int = ...
        Key_5: int = ...
        Key_6: int = ...
        Key_7: int = ...
        Key_8: int = ...
        Key_9: int = ...
        Key_Colon: int = ...
        Key_Semicolon: int = ...
        Key_Less: int = ...
        Key_Equal: int = ...
        Key_Greater: int = ...
        Key_Question: int = ...
        Key_At: int = ...
        Key_A: int = ...
        Key_B: int = ...
        Key_C: int = ...
        Key_D: int = ...
        Key_E: int = ...
        Key_F: int = ...
        Key_G: int = ...
        Key_H: int = ...
        Key_I: int = ...
        Key_J: int = ...
        Key_K: int = ...
        Key_L: int = ...
        Key_M: int = ...
        Key_N: int = ...
        Key_O: int = ...
        Key_P: int = ...
        Key_Q: int = ...
        Key_R: int = ...
        Key_S: int = ...
        Key_T: int = ...
        Key_U: int = ...
        Key_V: int = ...
        Key_W: int = ...
        Key_X: int = ...
        Key_Y: int = ...
        Key_Z: int = ...
        Key_BracketLeft: int = ...
        Key_Backslash: int = ...
        Key_BracketRight: int = ...
        Key_AsciiTilde: int = ...

class QSize:
    def __init__(self) -> None: ...
    def __init__(self, w: int, h: int) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isValid(self) -> bool: ...
    def expandedTo(self, other: 'QSize') -> 'QSize': ...
    def boundedTo(self, other: 'QSize') -> 'QSize': ...
    def __add__(self, other: 'QSize') -> 'QSize': ...
    def __sub__(self, other: 'QSize') -> 'QSize': ...
    def __mul__(self, factor: int) -> 'QSize': ...
    def __div__(self, factor: int) -> 'QSize': ...

class QPoint:
    def __init__(self) -> None: ...
    def __init__(self, x: int, y: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def isNull(self) -> bool: ...
    def manhattanLength(self) -> int: ...
    def __add__(self, other: 'QPoint') -> 'QPoint': ...
    def __sub__(self, other: 'QPoint') -> 'QPoint': ...
    def __mul__(self, factor: int) -> 'QPoint': ...
    def __div__(self, factor: int) -> 'QPoint': ...

class QRect:
    def __init__(self) -> None: ...
    def __init__(self, topLeft: QPoint, bottomRight: QPoint) -> None: ...
    def __init__(self, x: int, y: int, w: int, h: int) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def left(self) -> int: ...
    def right(self) -> int: ...
    def top(self) -> int: ...
    def bottom(self) -> int: ...
    def topLeft(self) -> QPoint: ...
    def bottomRight(self) -> QPoint: ...
    def topRight(self) -> QPoint: ...
    def bottomLeft(self) -> QPoint: ...
    def center(self) -> QPoint: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def setWidth(self, w: int) -> None: ...
    def setHeight(self, h: int) -> None: ...
    def setLeft(self, left: int) -> None: ...
    def setRight(self, right: int) -> None: ...
    def setTop(self, top: int) -> None: ...
    def setBottom(self, bottom: int) -> None: ...
    def setTopLeft(self, p: QPoint) -> None: ...
    def setBottomRight(self, p: QPoint) -> None: ...
    def setTopRight(self, p: QPoint) -> None: ...
    def setBottomLeft(self, p: QPoint) -> None: ...
    def setRect(self, x: int, y: int, w: int, h: int) -> None: ...
    def getRect(self) -> Tuple[int, int, int, int]: ...
    def setCoords(self, x1: int, y1: int, x2: int, y2: int) -> None: ...
    def getCoords(self) -> Tuple[int, int, int, int]: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isValid(self) -> bool: ...
    def contains(self, p: QPoint) -> bool: ...
    def contains(self, r: 'QRect') -> bool: ...
    def contains(self, x: int, y: int) -> bool: ...
    def unite(self, other: 'QRect') -> 'QRect': ...
    def intersect(self, other: 'QRect') -> 'QRect': ...
    def intersects(self, other: 'QRect') -> bool: ...
    def normalized(self) -> 'QRect': ...

class QDate:
    def __init__(self) -> None: ...
    def __init__(self, y: int, m: int, d: int) -> None: ...
    @staticmethod
    def currentDate() -> 'QDate': ...
    @staticmethod
    def fromString(string: str, format: str = ...) -> 'QDate': ...
    def year(self) -> int: ...
    def month(self) -> int: ...
    def day(self) -> int: ...
    def isValid(self) -> bool: ...
    def toString(self, format: str = ...) -> str: ...
    def addDays(self, days: int) -> 'QDate': ...
    def addMonths(self, months: int) -> 'QDate': ...
    def addYears(self, years: int) -> 'QDate': ...
    def daysTo(self, other: 'QDate') -> int: ...
    def __lt__(self, other: 'QDate') -> bool: ...
    def __le__(self, other: 'QDate') -> bool: ...
    def __eq__(self, other: 'QDate') -> bool: ...
    def __ne__(self, other: 'QDate') -> bool: ...
    def __gt__(self, other: 'QDate') -> bool: ...
    def __ge__(self, other: 'QDate') -> bool: ...

class QTime:
    def __init__(self) -> None: ...
    def __init__(self, h: int, m: int, s: int = 0, ms: int = 0) -> None: ...
    @staticmethod
    def currentTime() -> 'QTime': ...
    @staticmethod
    def fromString(string: str, format: str = ...) -> 'QTime': ...
    def hour(self) -> int: ...
    def minute(self) -> int: ...
    def second(self) -> int: ...
    def msec(self) -> int: ...
    def isValid(self) -> bool: ...
    def toString(self, format: str = ...) -> str: ...
    def addSecs(self, secs: int) -> 'QTime': ...
    def addMSecs(self, msecs: int) -> 'QTime': ...
    def secsTo(self, other: 'QTime') -> int: ...
    def msecsTo(self, other: 'QTime') -> int: ...

class QDateTime:
    def __init__(self) -> None: ...
    def __init__(self, date: QDate, time: QTime) -> None: ...
    @staticmethod
    def currentDateTime() -> 'QDateTime': ...
    @staticmethod
    def currentDateTimeUtc() -> 'QDateTime': ...
    @staticmethod
    def fromString(string: str, format: str = ...) -> 'QDateTime': ...
    def date(self) -> QDate: ...
    def time(self) -> QTime: ...
    def setDate(self, date: QDate) -> None: ...
    def setTime(self, time: QTime) -> None: ...
    def isValid(self) -> bool: ...
    def toString(self, format: str = ...) -> str: ...
    def toSecsSinceEpoch(self) -> int: ...
    @staticmethod
    def fromSecsSinceEpoch(secs: int) -> 'QDateTime': ...
    def addSecs(self, secs: int) -> 'QDateTime': ...
    def addDays(self, days: int) -> 'QDateTime': ...
    def addMonths(self, months: int) -> 'QDateTime': ...
    def addYears(self, years: int) -> 'QDateTime': ...

class QUrl:
    def __init__(self) -> None: ...
    def __init__(self, url: str) -> None: ...
    @staticmethod
    def fromUserInput(userInput: str) -> 'QUrl': ...
    def fromLocalFile(localfile: str) -> 'QUrl': ...
    def isLocalFile(self) -> bool: ...
    def toLocalFile(self) -> str: ...
    def toString(self, options: int = ...) -> str: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def scheme(self) -> str: ...
    def setScheme(self, scheme: str) -> None: ...
    def host(self) -> str: ...
    def setHost(self, host: str) -> None: ...
    def port(self) -> int: ...
    def setPort(self, port: int) -> None: ...
    def path(self) -> str: ...
    def setPath(self, path: str) -> None: ...
    def fileName(self) -> str: ...

    class FormattingOption:
        None_: int = ...
        PrettyDecoded: int = ...
        EncodeSpaces: int = ...
        EncodeUnicode: int = ...
        DecodeReserved: int = ...

class QLocale:
    def __init__(self) -> None: ...
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def system() -> 'QLocale': ...
    def name(self) -> str: ...
    def language(self) -> 'Language': ...
    def country(self) -> 'Country': ...
    def toString(self, i: int) -> str: ...
    def toString(self, f: float) -> str: ...
    def toString(self, d: QDate, format: str = ...) -> str: ...
    def toString(self, t: QTime, format: str = ...) -> str: ...
    def toInt(self, s: str, ok: Optional[int] = ...) -> int: ...
    def toFloat(self, s: str, ok: Optional[int] = ...) -> float: ...
    def toDate(self, s: str, format: str = ...) -> QDate: ...
    def toTime(self, s: str, format: str = ...) -> QTime: ...

    class Language:
        AnyLanguage: int = ...
        C: int = ...
        Abkhazian: int = ...
        Afan: int = ...
        Afrikaans: int = ...
        Albanian: int = ...
        Amharic: int = ...
        Arabic: int = ...
        Aragonese: int = ...
        Armenian: int = ...
        Assamese: int = ...
        Aymara: int = ...
        Azerbaijani: int = ...
        Bashkir: int = ...
        Basque: int = ...
        Bengali: int = ...
        Bhutani: int = ...
        Bihari: int = ...
        Bislama: int = ...
        Breton: int = ...
        Bulgarian: int = ...
        Burmese: int = ...
        Byelorussian: int = ...
        Cambodian: int = ...
        Catalan: int = ...
        Chinese: int = ...
        Croatian: int = ...
        Czech: int = ...
        Danish: int = ...
        Dutch: int = ...
        English: int = ...
        Esperanto: int = ...
        Estonian: int = ...
        Faroese: int = ...
        Farsi: int = ...
        Fiji: int = ...
        Finnish: int = ...
        French: int = ...
        Frisian: int = ...
        Gaelic: int = ...
        Galician: int = ...
        Georgian: int = ...
        German: int = ...
        Greek: int = ...
        Greenlandic: int = ...
        Guarani: int = ...
        Gujarati: int = ...
        Hausa: int = ...
        Hebrew: int = ...
        Hindi: int = ...
        Hungarian: int = ...
        Icelandic: int = ...
        Indonesian: int = ...
        Interlingua: int = ...
        Interlingue: int = ...
        Inupiak: int = ...
        Irish: int = ...
        Italian: int = ...
        Japanese: int = ...
        Javanese: int = ...
        Kannada: int = ...
        Kashmiri: int = ...
        Kazakh: int = ...
        Kinyarwanda: int = ...
        Kirghiz: int = ...
        Korean: int = ...
        Kurdish: int = ...
        Laothian: int = ...
        Latin: int = ...
        Latvian: int = ...
        Lingala: int = ...
        Lithuanian: int = ...
        Macedonian: int = ...
        Malagasy: int = ...
        Malay: int = ...
        Malayalam: int = ...
        Maltese: int = ...
        Maori: int = ...
        Marathi: int = ...
        Moldavian: int = ...
        Mongolian: int = ...
        NauruLanguage: int = ...
        Nepali: int = ...
        Norwegian: int = ...
        NorwegianBokmal: int = ...
        NorwegianNynorsk: int = ...
        Occitan: int = ...
        Oriya: int = ...
        Pashto: int = ...
        Polish: int = ...
        Portuguese: int = ...
        Punjabi: int = ...
        Quechua: int = ...
        RhaetoRomance: int = ...
        Romanian: int = ...
        Russian: int = ...
        Samoan: int = ...
        Sangho: int = ...
        Sanskrit: int = ...
        Serbian: int = ...
        SerboCroatian: int = ...
        Sesotho: int = ...
        Setswana: int = ...
        Shona: int = ...
        Sindhi: int = ...
        Singhalese: int = ...
        Siswati: int = ...
        Slovak: int = ...
        Slovenian: int = ...
        Somali: int = ...
        Spanish: int = ...
        Sundanese: int = ...
        Swahili: int = ...
        Swedish: int = ...
        Tajik: int = ...
        Tamil: int = ...
        Tatar: int = ...
        Telugu: int = ...
        Thai: int = ...
        Tibetan: int = ...
        Tigrinya: int = ...
        Tonga: int = ...
        Turkish: int = ...
        Turkmen: int = ...
        Twi: int = ...
        Uigur: int = ...
        Ukrainian: int = ...
        Urdu: int = ...
        Uzbek: int = ...
        Vietnamese: int = ...
        Volapuk: int = ...
        Welsh: int = ...
        Wolof: int = ...
        Xhosa: int = ...
        Yiddish: int = ...
        Yoruba: int = ...
        Zhuang: int = ...
        Zulu: int = ...

    class Country:
        AnyCountry: int = ...
        Afghanistan: int = ...
        Albania: int = ...
        Algeria: int = ...
        AmericanSamoa: int = ...
        Andorra: int = ...
        Angola: int = ...
        Anguilla: int = ...
        Antarctica: int = ...
        AntiguaAndBarbuda: int = ...
        Argentina: int = ...
        Armenia: int = ...
        Aruba: int = ...
        Australia: int = ...
        Austria: int = ...
        Azerbaijan: int = ...
        Bahamas: int = ...
        Bahrain: int = ...
        Bangladesh: int = ...
        Barbados: int = ...
        Belarus: int = ...
        Belgium: int = ...
        Belize: int = ...
        Benin: int = ...
        Bermuda: int = ...
        Bhutan: int = ...
        Bolivia: int = ...
        BosniaAndHerzegowina: int = ...
        Botswana: int = ...
        BouvetIsland: int = ...
        Brazil: int = ...
        BritishIndianOceanTerritory: int = ...
        BruneiDarussalam: int = ...
        Bulgaria: int = ...
        BurkinaFaso: int = ...
        Burundi: int = ...
        Cambodia: int = ...
        Cameroon: int = ...
        Canada: int = ...
        CapeVerde: int = ...
        CaymanIslands: int = ...
        CentralAfricanRepublic: int = ...
        Chad: int = ...
        Chile: int = ...
        China: int = ...
        ChristmasIsland: int = ...
        CocosIslands: int = ...
        Colombia: int = ...
        Comoros: int = ...
        Congo: int = ...
        CookIslands: int = ...
        CostaRica: int = ...
        CoteDIvoire: int = ...
        Croatia: int = ...
        Cuba: int = ...
        Cyprus: int = ...
        CzechRepublic: int = ...
        Denmark: int = ...
        Djibouti: int = ...
        Dominica: int = ...
        DominicanRepublic: int = ...
        EastTimor: int = ...
        Ecuador: int = ...
        Egypt: int = ...
        ElSalvador: int = ...
        EquatorialGuinea: int = ...
        Eritrea: int = ...
        Estonia: int = ...
        Ethiopia: int = ...
        FalklandIslands: int = ...
        FaroeIslands: int = ...
        Fiji: int = ...
        Finland: int = ...
        France: int = ...
        FrenchGuiana: int = ...
        FrenchPolynesia: int = ...
        FrenchSouthernTerritories: int = ...
        Gabon: int = ...
        Gambia: int = ...
        Georgia: int = ...
        Germany: int = ...
        Ghana: int = ...
        Gibraltar: int = ...
        Greece: int = ...
        Greenland: int = ...
        Grenada: int = ...
        Guadeloupe: int = ...
        Guam: int = ...
        Guatemala: int = ...
        Guinea: int = ...
        GuineaBissau: int = ...
        Guyana: int = ...
        Haiti: int = ...
        HeardAndMcDonaldIslands: int = ...
        Honduras: int = ...
        HongKong: int = ...
        Hungary: int = ...
        Iceland: int = ...
        India: int = ...
        Indonesia: int = ...
        Iran: int = ...
        Iraq: int = ...
        Ireland: int = ...
        Israel: int = ...
        Italy: int = ...
        Jamaica: int = ...
        Japan: int = ...
        Jordan: int = ...
        Kazakhstan: int = ...
        Kenya: int = ...
        Kiribati: int = ...
        DemocraticRepublicOfKorea: int = ...
        RepublicOfKorea: int = ...
        Kuwait: int = ...
        Kyrgyzstan: int = ...
        Laos: int = ...
        Latvia: int = ...
        Lebanon: int = ...
        Lesotho: int = ...
        Liberia: int = ...
        LibyanArabJamahiriya: int = ...
        Liechtenstein: int = ...
        Lithuania: int = ...
        Luxembourg: int = ...
        Macau: int = ...
        Madagascar: int = ...
        Malawi: int = ...
        Malaysia: int = ...
        Maldives: int = ...
        Mali: int = ...
        Malta: int = ...
        MarshallIslands: int = ...
        Martinique: int = ...
        Mauritania: int = ...
        Mauritius: int = ...
        Mayotte: int = ...
        Mexico: int = ...
        Micronesia: int = ...
        Moldova: int = ...
        Monaco: int = ...
        Mongolia: int = ...
        Montserrat: int = ...
        Morocco: int = ...
        Mozambique: int = ...
        Myanmar: int = ...
        Namibia: int = ...
        Nauru: int = ...
        Nepal: int = ...
        Netherlands: int = ...
        NetherlandsAntilles: int = ...
        NewCaledonia: int = ...
        NewZealand: int = ...
        Nicaragua: int = ...
        Niger: int = ...
        Nigeria: int = ...
        Niue: int = ...
        NorfolkIsland: int = ...
        NorthernMarianaIslands: int = ...
        Norway: int = ...
        Oman: int = ...
        Pakistan: int = ...
        Palau: int = ...
        PalestinianTerritory: int = ...
        Panama: int = ...
        PapuaNewGuinea: int = ...
        Paraguay: int = ...
        Peru: int = ...
        Philippines: int = ...
        Pitcairn: int = ...
        Poland: int = ...
        Portugal: int = ...
        PuertoRico: int = ...
        Qatar: int = ...
        Reunion: int = ...
        Romania: int = ...
        RussianFederation: int = ...
        Rwanda: int = ...
        SaintKittsAndNevis: int = ...
        SaintLucia: int = ...
        SaintVincentAndTheGrenadines: int = ...
        Samoa: int = ...
        SanMarino: int = ...
        SaoTomeAndPrincipe: int = ...
        SaudiArabia: int = ...
        Senegal: int = ...
        Seychelles: int = ...
        SierraLeone: int = ...
        Singapore: int = ...
        Slovakia: int = ...
        Slovenia: int = ...
        SolomonIslands: int = ...
        Somalia: int = ...
        SouthAfrica: int = ...
        SouthGeorgiaAndTheSouthSandwichIslands: int = ...
        Spain: int = ...
        SriLanka: int = ...
        StHelena: int = ...
        StPierreAndMiquelon: int = ...
        Sudan: int = ...
        Suriname: int = ...
        SvalbardAndJanMayenIslands: int = ...
        Swaziland: int = ...
        Sweden: int = ...
        Switzerland: int = ...
        SyrianArabRepublic: int = ...
        Taiwan: int = ...
        Tajikistan: int = ...
        Tanzania: int = ...
        Thailand: int = ...
        Togo: int = ...
        Tokelau: int = ...
        Tonga: int = ...
        TrinidadAndTobago: int = ...
        Tunisia: int = ...
        Turkey: int = ...
        Turkmenistan: int = ...
        TurksAndCaicosIslands: int = ...
        Tuvalu: int = ...
        Uganda: int = ...
        Ukraine: int = ...
        UnitedArabEmirates: int = ...
        UnitedKingdom: int = ...
        UnitedStates: int = ...
        UnitedStatesMinorOutlyingIslands: int = ...
        Uruguay: int = ...
        Uzbekistan: int = ...
        Vanuatu: int = ...
        VaticanCityState: int = ...
        Venezuela: int = ...
        VietNam: int = ...
        VirginIslandsBritish: int = ...
        VirginIslandsUS: int = ...
        WallisAndFutunaIslands: int = ...
        WesternSahara: int = ...
        Yemen: int = ...
        Yugoslavia: int = ...
        Zambia: int = ...
        Zimbabwe: int = ...

class QTranslator(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def load(self, filename: str, directory: str = "", search_delimiters: str = "", suffix: str = "") -> bool: ...
    def translate(self, context: str, sourceText: str, disambiguation: str = ..., n: int = ...) -> str: ...

class QThread(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def start(self, priority: 'Priority' = ...) -> None: ...
    def terminate(self) -> None: ...
    def exit(self, returnCode: int = 0) -> None: ...
    def wait(self, msecs: int = ...) -> bool: ...
    def isRunning(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def sleep(self, secs: int) -> None: ...
    def msleep(self, msecs: int) -> None: ...
    def usleep(self, usecs: int) -> None: ...
    @staticmethod
    def currentThread() -> 'QThread': ...
    @staticmethod
    def idealParallelCount() -> int: ...

    class Priority:
        IdlePriority: int = ...
        LowestPriority: int = ...
        LowPriority: int = ...
        NormalPriority: int = ...
        HighPriority: int = ...
        HighestPriority: int = ...
        TimeCriticalPriority: int = ...
        InheritPriority: int = ...

class QEvent:
    def __init__(self, type: 'Type') -> None: ...
    def type(self) -> 'Type': ...
    def spontaneous(self) -> bool: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def setAccepted(self, accepted: bool) -> None: ...

    class Type:
        None_: int = ...
        Timer: int = ...
        MouseButtonPress: int = ...
        MouseButtonRelease: int = ...
        MouseButtonDblClick: int = ...
        MouseMove: int = ...
        KeyPress: int = ...
        KeyRelease: int = ...
        FocusIn: int = ...
        FocusOut: int = ...
        FocusAboutToChange: int = ...
        Enter: int = ...
        Leave: int = ...
        Paint: int = ...
        Move: int = ...
        Resize: int = ...
        Create: int = ...
        Destroy: int = ...
        Show: int = ...
        Hide: int = ...
        Close: int = ...
        Quit: int = ...
        ParentChange: int = ...
        ParentAboutToChange: int = ...
        ThreadChange: int = ...
        WindowActivate: int = ...
        WindowDeactivate: int = ...
        ShowToParent: int = ...
        HideToParent: int = ...
        Wheel: int = ...
        WindowTitleChange: int = ...
        WindowIconChange: int = ...
        ApplicationWindowIconChange: int = ...
        ApplicationFontChange: int = ...
        ApplicationPaletteChange: int = ...
        PaletteChange: int = ...
        Clipboard: int = ...
        Speech: int = ...
        MetaCall: int = ...
        SockAct: int = ...
        WinEventAct: int = ...
        DeferredDelete: int = ...
        DragEnter: int = ...
        DragMove: int = ...
        DragLeave: int = ...
        Drop: int = ...
        DragResponse: int = ...
        ChildAdded: int = ...
        ChildPolished: int = ...
        ChildRemoved: int = ...
        ShowWindowRequest: int = ...
        PolishRequest: int = ...
        Polish: int = ...
        LayoutRequest: int = ...
        UpdateRequest: int = ...
        UpdateLater: int = ...
        EmbeddingControl: int = ...
        ActivateControl: int = ...
        DeactivateControl: int = ...
        ContextMenu: int = ...
        InputMethod: int = ...
        TabletMove: int = ...
        LocaleChange: int = ...
        LanguageChange: int = ...
        LayoutDirectionChange: int = ...
        Style: int = ...
        TabletPress: int = ...
        TabletRelease: int = ...
        OkRequest: int = ...
        HelpRequest: int = ...
        IconDrag: int = ...
        FontChange: int = ...
        EnabledChange: int = ...
        ActivationChange: int = ...
        FontChange: int = ...
        StyleChange: int = ...
        CursorChange: int = ...
        Tooltip: int = ...
        StatusTip: int = ...
        WhatsThis: int = ...
        EnterEditFocus: int = ...
        LeaveEditFocus: int = ...
        Accept: int = ...
        Cancel: int = ...
        FocusIn: int = ...
        FocusOut: int = ...
        Shortcut: int = ...
        ShortcutOverride: int = ...
        WhatsThisClicked: int = ...
        ToolBarChange: int = ...
        ApplicationActivated: int = ...
        ApplicationDeactivated: int = ...
        ApplicationStateChanged: int = ...
        WindowBlocked: int = ...
        WindowUnblocked: int = ...
        WindowStateChange: int = ...
        WindowTitleChange: int = ...
        WindowIconChange: int = ...
        ApplicationWindowIconChange: int = ...
        ScrollBarChange: int = ...
        Scroll: int = ...
        Gesture: int = ...
        GestureOverride: int = ...
        TouchBegin: int = ...
        TouchUpdate: int = ...
        TouchEnd: int = ...
        NativeGesture: int = ...
        RequestSoftwareInputPanel: int = ...
        CloseSoftwareInputPanel: int = ...
        OrientationChange: int = ...

class QMetaObject:
    def className(self) -> str: ...
    def superClass(self) -> Optional['QMetaObject']: ...
    def methodCount(self) -> int: ...
    def methodOffset(self) -> int: ...
    def enumeratorCount(self) -> int: ...
    def enumeratorOffset(self) -> int: ...
    def propertyCount(self) -> int: ...
    def propertyOffset(self) -> int: ...
    def classInfoCount(self) -> int: ...
    def classInfoOffset(self) -> int: ...
    def invokeMethod(self, obj: QObject, member: str, type: Any = ..., ret: Any = ..., val0: Any = ..., val1: Any = ..., val2: Any = ..., val3: Any = ..., val4: Any = ..., val5: Any = ..., val6: Any = ..., val7: Any = ..., val8: Any = ..., val9: Any = ...) -> bool: ...

class QSizePolicy:
    def __init__(self) -> None: ...
    def __init__(self, horizontal: 'Policy', vertical: 'Policy') -> None: ...
    def horizontalPolicy(self) -> 'Policy': ...
    def verticalPolicy(self) -> 'Policy': ...
    def setHorizontalPolicy(self, policy: 'Policy') -> None: ...
    def setVerticalPolicy(self, policy: 'Policy') -> None: ...
    def horizontalStretch(self) -> int: ...
    def verticalStretch(self) -> int: ...
    def setHorizontalStretch(self, stretchFactor: int) -> None: ...
    def setVerticalStretch(self, stretchFactor: int) -> None: ...
    def controlType(self) -> 'ControlType': ...
    def setControlType(self, type: 'ControlType') -> None: ...
    def transpose(self) -> None: ...
    def transposed(self) -> 'QSizePolicy': ...
    def retainSizeWhenHidden(self) -> bool: ...
    def setRetainSizeWhenHidden(self, retainSize: bool) -> None: ...

    class Policy:
        Fixed: int = ...
        Minimum: int = ...
        Maximum: int = ...
        Preferred: int = ...
        Expanding: int = ...
        MinimumExpanding: int = ...
        Ignored: int = ...

    class ControlType:
        DefaultType: int = ...
        ButtonBox: int = ...
        CheckBox: int = ...
        ComboBox: int = ...
        Frame: int = ...
        GroupBox: int = ...
        Label: int = ...
        Line: int = ...
        LineEdit: int = ...
        PushButton: int = ...
        RadioButton: int = ...
        Slider: int = ...
        SpinBox: int = ...
        TabWidget: int = ...
        ToolButton: int = ...
