"""
Type stubs for PySide6.QtGui
Generated for modorganizer-linux project
"""

from typing import Any, Optional, List, Union, Tuple
from PySide6.QtCore import QObject, QSize, QRect, QPoint, Qt, QEvent

class QAction(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def __init__(self, text: str, parent: Optional[QObject] = None) -> None: ...
    def __init__(
        self, icon: "QIcon", text: str, parent: Optional[QObject] = None
    ) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: "QIcon") -> None: ...
    def icon(self) -> "QIcon": ...
    def setIconText(self, text: str) -> None: ...
    def iconText(self) -> str: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setStatusTip(self, tip: str) -> None: ...
    def statusTip(self) -> str: ...
    def setWhatsThis(self, what: str) -> None: ...
    def whatsThis(self) -> str: ...
    def setShortcut(self, shortcut: Union[str, "QKeySequence"]) -> None: ...
    def shortcut(self) -> "QKeySequence": ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def setSeparator(self, separator: bool) -> None: ...
    def isSeparator(self) -> bool: ...
    def setData(self, data: Any) -> None: ...
    def data(self) -> Any: ...
    def setPriority(self, priority: "Priority") -> None: ...
    def priority(self) -> "Priority": ...
    def setMenu(self, menu: "QMenu") -> None: ...
    def menu(self) -> Optional["QMenu"]: ...
    def trigger(self) -> None: ...
    def toggle(self) -> None: ...
    def hover(self) -> None: ...

    class Priority:
        LowPriority: int = ...
        NormalPriority: int = ...
        HighPriority: int = ...

class QIcon:
    def __init__(self) -> None: ...
    def __init__(self, pixmap: "QPixmap") -> None: ...
    def __init__(self, fileName: str) -> None: ...
    @staticmethod
    def fromTheme(name: str) -> "QIcon": ...
    @staticmethod
    def fromTheme(name: str, fallback: "QIcon") -> "QIcon": ...
    def isNull(self) -> bool: ...
    def isDetached(self) -> bool: ...
    def addPixmap(
        self, pixmap: "QPixmap", mode: "QIcon.Mode" = ..., state: "QIcon.State" = ...
    ) -> None: ...
    def addFile(
        self,
        fileName: str,
        size: QSize = ...,
        mode: "QIcon.Mode" = ...,
        state: "QIcon.State" = ...,
    ) -> None: ...
    def pixmap(
        self, size: QSize, mode: "QIcon.Mode" = ..., state: "QIcon.State" = ...
    ) -> "QPixmap": ...
    def actualSize(
        self, size: QSize, mode: "QIcon.Mode" = ..., state: "QIcon.State" = ...
    ) -> QSize: ...
    def name(self) -> str: ...
    def paint(
        self,
        painter: "QPainter",
        rect: QRect,
        alignment: Qt.AlignmentFlag = ...,
        mode: "QIcon.Mode" = ...,
        state: "QIcon.State" = ...,
    ) -> None: ...

    class Mode:
        Normal: int = ...
        Disabled: int = ...
        Active: int = ...
        Selected: int = ...

    class State:
        On: int = ...
        Off: int = ...

class QPixmap:
    def __init__(self) -> None: ...
    def __init__(self, fileName: str) -> None: ...
    def __init__(self, size: QSize) -> None: ...
    @staticmethod
    def fromImage(image: "QImage") -> "QPixmap": ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def rect(self) -> QRect: ...
    def load(self, fileName: str, format: str = ...) -> bool: ...
    def loadFromData(self, data: bytes, format: str = ...) -> bool: ...
    def save(self, fileName: str, format: str = ..., quality: int = ...) -> bool: ...
    def toImage(self) -> "QImage": ...
    def scaled(
        self,
        w: int,
        h: int,
        aspectMode: "Qt.AspectRatioMode" = ...,
        transformMode: "Qt.TransformationMode" = ...,
    ) -> "QPixmap": ...
    def scaledToWidth(
        self, width: int, transformMode: "Qt.TransformationMode" = ...
    ) -> "QPixmap": ...
    def scaledToHeight(
        self, height: int, transformMode: "Qt.TransformationMode" = ...
    ) -> "QPixmap": ...

class QImage:
    def __init__(self) -> None: ...
    def __init__(self, size: QSize, format: "Format") -> None: ...
    def __init__(self, width: int, height: int, format: "Format") -> None: ...
    def __init__(self, fileName: str) -> None: ...
    @staticmethod
    def fromData(data: bytes) -> "QImage": ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def rect(self) -> QRect: ...
    def bits(self) -> Any: ...
    def byteCount(self) -> int: ...
    def bytesPerLine(self) -> int: ...
    def depth(self) -> int: ...
    def format(self) -> "Format": ...
    def load(self, fileName: str) -> bool: ...
    def save(self, fileName: str, format: str = ..., quality: int = ...) -> bool: ...
    def convertToFormat(self, format: "Format") -> "QImage": ...
    def scaled(
        self,
        w: int,
        h: int,
        aspectMode: "Qt.AspectRatioMode" = ...,
        transformMode: "Qt.TransformationMode" = ...,
    ) -> "QImage": ...
    def copy(self, rect: QRect = ...) -> "QImage": ...
    def fill(self, color: Union["QColor", "QGradient", int]) -> None: ...

    class Format:
        Format_Invalid: int = ...
        Format_Mono: int = ...
        Format_MonoLSB: int = ...
        Format_Indexed8: int = ...
        Format_RGB32: int = ...
        Format_ARGB32: int = ...
        Format_ARGB32_Premultiplied: int = ...
        Format_RGB16: int = ...
        Format_ARGB8565_Premultiplied: int = ...
        Format_RGB666: int = ...
        Format_ARGB6666_Premultiplied: int = ...
        Format_RGB555: int = ...
        Format_ARGB8555_Premultiplied: int = ...
        Format_RGB888: int = ...
        Format_RGB444: int = ...
        Format_ARGB4444_Premultiplied: int = ...
        Format_RGBX8888: int = ...
        Format_RGBA8888: int = ...
        Format_RGBA8888_Premultiplied: int = ...
        Format_BGR30: int = ...
        Format_A2BGR30_Premultiplied: int = ...
        Format_RGB30: int = ...
        Format_A2RGB30_Premultiplied: int = ...
        Format_Alpha8: int = ...
        Format_Grayscale8: int = ...
        Format_RGBX64: int = ...
        Format_RGBA64: int = ...
        Format_RGBA64_Premultiplied: int = ...
        Format_Grayscale16: int = ...
        Format_BGR888: int = ...

class QColor:
    def __init__(self) -> None: ...
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...
    def __init__(self, color: Qt.GlobalColor) -> None: ...
    def __init__(
        self, spec: "Spec", a1: float, a2: float, a3: float, a4: float = 1.0
    ) -> None: ...
    @staticmethod
    def fromRgb(r: int, g: int, b: int, a: int = 255) -> "QColor": ...
    @staticmethod
    def fromRgba(r: int, g: int, b: int, a: int) -> "QColor": ...
    @staticmethod
    def fromHsl(h: int, s: int, l: int, a: int = 255) -> "QColor": ...
    @staticmethod
    def fromHsv(h: int, s: int, v: int, a: int = 255) -> "QColor": ...
    @staticmethod
    def fromCmyk(c: int, m: int, y: int, k: int, a: int = 255) -> "QColor": ...
    @staticmethod
    def fromString(name: str) -> "QColor": ...
    def spec(self) -> "Spec": ...
    def alpha(self) -> int: ...
    def setAlpha(self, alpha: int) -> None: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def rgb(self) -> int: ...
    def setRgb(self, r: int, g: int, b: int, a: int = 255) -> None: ...
    def hue(self) -> int: ...
    def saturation(self) -> int: ...
    def value(self) -> int: ...
    def hsv(self) -> Tuple[int, int, int]: ...
    def setHsv(self, h: int, s: int, v: int, a: int = 255) -> None: ...
    def lightness(self) -> int: ...
    def hsl(self) -> Tuple[int, int, int]: ...
    def setHsl(self, h: int, s: int, l: int, a: int = 255) -> None: ...
    def cyan(self) -> int: ...
    def magenta(self) -> int: ...
    def yellow(self) -> int: ...
    def black(self) -> int: ...
    def cmyk(self) -> Tuple[int, int, int, int]: ...
    def setCmyk(self, c: int, m: int, y: int, k: int, a: int = 255) -> None: ...
    def name(self) -> str: ...
    def isValid(self) -> bool: ...
    def lighter(self, factor: int = 150) -> "QColor": ...
    def darker(self, factor: int = 200) -> "QColor": ...

    class Spec:
        Invalid: int = ...
        Rgb: int = ...
        Hsv: int = ...
        Cmyk: int = ...
        Hsl: int = ...

class QBrush:
    def __init__(self) -> None: ...
    def __init__(self, color: QColor) -> None: ...
    def __init__(self, color: Qt.GlobalColor) -> None: ...
    def __init__(self, gradient: "QGradient") -> None: ...
    def __init__(self, image: QImage) -> None: ...
    def __init__(self, pixmap: QPixmap) -> None: ...
    def style(self) -> "Qt.BrushStyle": ...
    def setStyle(self, style: "Qt.BrushStyle") -> None: ...
    def color(self) -> QColor: ...
    def setColor(self, color: QColor) -> None: ...
    def gradient(self) -> Optional["QGradient"]: ...
    def texture(self) -> QPixmap: ...
    def setTexture(self, pixmap: QPixmap) -> None: ...
    def isOpaque(self) -> bool: ...

class QGradient:
    def __init__(self) -> None: ...
    def type(self) -> "Type": ...
    def setSpread(self, spread: "Spread") -> None: ...
    def spread(self) -> "Spread": ...
    def setColorAt(self, position: float, color: QColor) -> None: ...
    def stops(self) -> List[Tuple[float, QColor]]: ...

    class Type:
        LinearGradient: int = ...
        RadialGradient: int = ...
        ConicalGradient: int = ...

    class Spread:
        PadSpread: int = ...
        ReflectSpread: int = ...
        RepeatSpread: int = ...

class QLinearGradient(QGradient):
    def __init__(self) -> None: ...
    def __init__(self, start: QPointF, finalStop: QPointF) -> None: ...
    def __init__(
        self, xStart: float, yStart: float, xFinalStop: float, yFinalStop: float
    ) -> None: ...
    def start(self) -> QPointF: ...
    def setStart(self, x: float, y: float) -> None: ...
    def setStart(self, start: QPointF) -> None: ...
    def finalStop(self) -> QPointF: ...
    def setFinalStop(self, x: float, y: float) -> None: ...
    def setFinalStop(self, stop: QPointF) -> None: ...

class QRadialGradient(QGradient):
    def __init__(self) -> None: ...
    def __init__(self, center: QPointF, radius: float) -> None: ...
    def __init__(self, centerX: float, centerY: float, radius: float) -> None: ...
    def center(self) -> QPointF: ...
    def setCenter(self, center: QPointF) -> None: ...
    def setCenter(self, x: float, y: float) -> None: ...
    def focalPoint(self) -> QPointF: ...
    def setFocalPoint(self, focalPoint: QPointF) -> None: ...
    def setFocalPoint(self, x: float, y: float) -> None: ...
    def radius(self) -> float: ...
    def setRadius(self, radius: float) -> None: ...

class QConicalGradient(QGradient):
    def __init__(self) -> None: ...
    def __init__(self, center: QPointF, angle: float) -> None: ...
    def __init__(self, centerX: float, centerY: float, angle: float) -> None: ...
    def center(self) -> QPointF: ...
    def setCenter(self, center: QPointF) -> None: ...
    def setCenter(self, x: float, y: float) -> None: ...
    def angle(self) -> float: ...
    def setAngle(self, angle: float) -> None: ...

class QCursor:
    def __init__(self) -> None: ...
    def __init__(self, shape: Qt.CursorShape) -> None: ...
    def __init__(
        self, bitmap: QPixmap, mask: QPixmap, hotX: int = -1, hotY: int = -1
    ) -> None: ...
    @staticmethod
    def pos() -> QPoint: ...
    @staticmethod
    def setPos(p: QPoint) -> None: ...
    @staticmethod
    def setPos(x: int, y: int) -> None: ...
    def shape(self) -> Qt.CursorShape: ...
    def setShape(self, shape: Qt.CursorShape) -> None: ...
    def bitmap(self) -> QPixmap: ...
    def mask(self) -> QPixmap: ...
    def hotSpot(self) -> QPoint: ...
    def setHotSpot(self, hotSpot: QPoint) -> None: ...
    @staticmethod
    def setOverrideCursor(cursor: "QCursor") -> None: ...
    @staticmethod
    def overrideCursor() -> "QCursor": ...
    @staticmethod
    def restoreOverrideCursor() -> None: ...

class QFont:
    def __init__(self) -> None: ...
    def __init__(
        self, family: str, pointSize: int = -1, weight: int = -1, italic: bool = False
    ) -> None: ...
    def __init__(self, font: "QFont") -> None: ...
    @staticmethod
    def font(fontInfo: "QFontInfo") -> "QFont": ...
    def family(self) -> str: ...
    def setFamily(self, family: str) -> None: ...
    def styleName(self) -> str: ...
    def setStyleName(self, styleName: str) -> None: ...
    def pointSize(self) -> int: ...
    def setPointSize(self, size: int) -> None: ...
    def pixelSize(self) -> int: ...
    def setPixelSize(self, size: int) -> None: ...
    def weight(self) -> int: ...
    def setWeight(self, weight: int) -> None: ...
    def bold(self) -> bool: ...
    def setBold(self, bold: bool) -> None: ...
    def italic(self) -> bool: ...
    def setItalic(self, italic: bool) -> None: ...
    def underline(self) -> bool: ...
    def setUnderline(self, underline: bool) -> None: ...
    def overline(self) -> bool: ...
    def setOverline(self, overline: bool) -> None: ...
    def strikeOut(self) -> bool: ...
    def setStrikeOut(self, strikeOut: bool) -> None: ...
    def fixedPitch(self) -> bool: ...
    def setFixedPitch(self, fixedPitch: bool) -> None: ...
    def kerning(self) -> bool: ...
    def setKerning(self, enable: bool) -> None: ...
    def style(self) -> "Style": ...
    def styleHint(self) -> "StyleHint": ...
    def exactMatch(self) -> bool: ...
    def isCopyOf(self, font: "QFont") -> bool: ...

    class Style:
        StyleNormal: int = ...
        StyleItalic: int = ...
        StyleOblique: int = ...

    class StyleHint:
        Helvetica: int = ...
        SansSerif: int = ...
        Serif: int = ...
        TypeWriter: int = ...
        OldEnglish: int = ...
        System: int = ...
        AnyStyle: int = ...
        Cursive: int = ...
        Fantasy: int = ...
        Monospace: int = ...

class QFontInfo:
    def __init__(self, font: QFont) -> None: ...
    def family(self) -> str: ...
    def styleName(self) -> str: ...
    def pixelSize(self) -> int: ...
    def pointSize(self) -> int: ...
    def weight(self) -> int: ...
    def italic(self) -> bool: ...
    def bold(self) -> bool: ...
    def underline(self) -> bool: ...
    def overline(self) -> bool: ...
    def strikeOut(self) -> bool: ...
    def fixedPitch(self) -> bool: ...
    def style(self) -> QFont.Style: ...
    def exactMatch(self) -> bool: ...

class QFontDatabase:
    def __init__(self) -> None: ...
    @staticmethod
    def families(writingSystem: "WritingSystem" = ...) -> List[str]: ...
    @staticmethod
    def styles(family: str) -> List[str]: ...
    @staticmethod
    def pointSizes(family: str, style: str = "") -> List[int]: ...
    @staticmethod
    def bold(family: str, style: str) -> bool: ...
    @staticmethod
    def italic(family: str, style: str) -> bool: ...
    @staticmethod
    def isFixedPitch(family: str, style: str = "") -> bool: ...
    @staticmethod
    def writingSystem(family: str) -> "WritingSystem": ...
    @staticmethod
    def writingSystems() -> List["WritingSystem"]: ...
    @staticmethod
    def font(family: str, style: str, pointSize: int) -> QFont: ...

    class WritingSystem:
        Any: int = ...
        Latin: int = ...
        Greek: int = ...
        Cyrillic: int = ...
        Armenian: int = ...
        Hebrew: int = ...
        Arabic: int = ...
        Syriac: int = ...
        Thaana: int = ...
        Devanagari: int = ...
        Bengali: int = ...
        Gurmukhi: int = ...
        Gujarati: int = ...
        Oriya: int = ...
        Tamil: int = ...
        Telugu: int = ...
        Kannada: int = ...
        Malayalam: int = ...
        Sinhala: int = ...
        Thai: int = ...
        Lao: int = ...
        Tibetan: int = ...
        Myanmar: int = ...
        Georgian: int = ...
        Khmer: int = ...
        SimplifiedChinese: int = ...
        TraditionalChinese: int = ...
        Japanese: int = ...
        Korean: int = ...
        Vietnamese: int = ...
        Symbol: int = ...
        Ogham: int = ...
        Runic: int = ...
        Nko: int = ...

class QKeySequence:
    def __init__(self) -> None: ...
    def __init__(self, key: str) -> None: ...
    def __init__(self, key: int) -> None: ...
    def __init__(self, key: int, modifiers: Qt.KeyboardModifier) -> None: ...
    @staticmethod
    def fromString(str: str) -> "QKeySequence": ...
    def toString(self, format: "SequenceFormat" = ...) -> str: ...
    def count(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def matches(self, seq: "QKeySequence") -> "SequenceMatch": ...

    class StandardKey:
        UnknownKey: int = ...
        HelpContents: int = ...
        WhatsThis: int = ...
        Open: int = ...
        Close: int = ...
        Save: int = ...
        New: int = ...
        Delete: int = ...
        Cut: int = ...
        Copy: int = ...
        Paste: int = ...
        Undo: int = ...
        Redo: int = ...
        Back: int = ...
        Forward: int = ...
        Refresh: int = ...
        ZoomIn: int = ...
        ZoomOut: int = ...
        Print: int = ...
        AddTab: int = ...
        NextChild: int = ...
        PreviousChild: int = ...
        Find: int = ...
        FindNext: int = ...
        FindPrevious: int = ...
        Replace: int = ...
        SelectAll: int = ...
        Bold: int = ...
        Italic: int = ...
        Underline: int = ...
        MoveToNextChar: int = ...
        MoveToPreviousChar: int = ...
        MoveToNextWord: int = ...
        MoveToPreviousWord: int = ...
        MoveToNextLine: int = ...
        MoveToPreviousLine: int = ...
        MoveToNextPage: int = ...
        MoveToPreviousPage: int = ...
        MoveToStartOfLine: int = ...
        MoveToEndOfLine: int = ...
        MoveToStartOfBlock: int = ...
        MoveToEndOfBlock: int = ...
        MoveToStartOfDocument: int = ...
        MoveToEndOfDocument: int = ...
        SelectNextChar: int = ...
        SelectPreviousChar: int = ...
        SelectNextWord: int = ...
        SelectPreviousWord: int = ...
        SelectNextLine: int = ...
        SelectPreviousLine: int = ...
        SelectNextPage: int = ...
        SelectPreviousPage: int = ...
        SelectStartOfLine: int = ...
        SelectEndOfLine: int = ...
        SelectStartOfBlock: int = ...
        SelectEndOfBlock: int = ...
        SelectStartOfDocument: int = ...
        SelectEndOfDocument: int = ...
        DeleteStartOfWord: int = ...
        DeleteEndOfWord: int = ...
        DeleteStartOfLine: int = ...
        DeleteEndOfLine: int = ...
        DeleteCompleteLine: int = ...
        InsertParagraphSeparator: int = ...
        InsertLineSeparator: int = ...
        SaveAs: int = ...
        Preferences: int = ...
        Quit: int = ...
        FullScreen: int = ...
        Deselect: int = ...
        DeleteCompleteWord: int = ...
        Cancel: int = ...

    class SequenceFormat:
        NativeText: int = ...
        PortableText: int = ...

    class SequenceMatch:
        NoMatch: int = ...
        PartialMatch: int = ...
        ExactMatch: int = ...

class QPalette:
    def __init__(self) -> None: ...
    def __init__(self, button: QColor, window: QColor) -> None: ...
    def colorGroup(self, group: "ColorGroup") -> "QPalette": ...
    def color(self, group: "ColorGroup", role: "ColorRole") -> QColor: ...
    def setColor(
        self, group: "ColorGroup", role: "ColorRole", color: QColor
    ) -> None: ...
    def setColor(self, role: "ColorRole", color: QColor) -> None: ...
    def brush(self, group: "ColorGroup", role: "ColorRole") -> QBrush: ...
    def setBrush(
        self, group: "ColorGroup", role: "ColorRole", brush: QBrush
    ) -> None: ...
    def setBrush(self, role: "ColorRole", brush: QBrush) -> None: ...
    def windowText(self) -> QColor: ...
    def button(self) -> QColor: ...
    def light(self) -> QColor: ...
    def dark(self) -> QColor: ...
    def mid(self) -> QColor: ...
    def text(self) -> QColor: ...
    def base(self) -> QColor: ...
    def window(self) -> QColor: ...
    def midlight(self) -> QColor: ...
    def highlight(self) -> QColor: ...
    def highlightedText(self) -> QColor: ...
    def link(self) -> QColor: ...
    def linkVisited(self) -> QColor: ...

    class ColorGroup:
        Active: int = ...
        Disabled: int = ...
        Inactive: int = ...
        Normal: int = ...
        All: int = ...
        Current: int = ...

    class ColorRole:
        WindowText: int = ...
        Button: int = ...
        Light: int = ...
        Midlight: int = ...
        Dark: int = ...
        Mid: int = ...
        Text: int = ...
        BrightText: int = ...
        ButtonText: int = ...
        Base: int = ...
        Window: int = ...
        Shadow: int = ...
        Highlight: int = ...
        HighlightedText: int = ...
        Link: int = ...
        LinkVisited: int = ...
        AlternateBase: int = ...
        NoRole: int = ...
        ToolTipBase: int = ...
        ToolTipText: int = ...
        PlaceholderText: int = ...
        NColorRoles: int = ...
        Foreground: int = ...
        Background: int = ...

class QPainter:
    def __init__(self) -> None: ...
    def __init__(self, device: "QPaintDevice") -> None: ...
    def begin(self, device: "QPaintDevice") -> bool: ...
    def end(self) -> bool: ...
    def isActive(self) -> bool: ...
    def device(self) -> Optional["QPaintDevice"]: ...
    def setPen(self, pen: "QPen") -> None: ...
    def setPen(self, color: QColor) -> None: ...
    def setPen(self, style: Qt.PenStyle) -> None: ...
    def pen(self) -> "QPen": ...
    def setBrush(self, brush: QBrush) -> None: ...
    def setBrush(self, color: QColor) -> None: ...
    def brush(self) -> QBrush: ...
    def setBackground(self, bg: QBrush) -> None: ...
    def background(self) -> QBrush: ...
    def setBackgroundMode(self, mode: Qt.BGMode) -> None: ...
    def backgroundMode(self) -> Qt.BGMode: ...
    def setFont(self, font: QFont) -> None: ...
    def font(self) -> QFont: ...
    def drawPoint(self, p: QPointF) -> None: ...
    def drawPoint(self, x: float, y: float) -> None: ...
    def drawPoints(self, points: List[QPointF]) -> None: ...
    def drawLine(self, line: "QLineF") -> None: ...
    def drawLine(self, p1: QPointF, p2: QPointF) -> None: ...
    def drawLine(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def drawLines(self, lines: List["QLineF"]) -> None: ...
    def drawPolyline(self, points: List[QPointF]) -> None: ...
    def drawPolygon(
        self, points: List[QPointF], fillRule: Qt.FillRule = ...
    ) -> None: ...
    def drawRect(self, rect: QRectF) -> None: ...
    def drawRect(self, x: float, y: float, w: float, h: float) -> None: ...
    def drawRects(self, rects: List[QRectF]) -> None: ...
    def drawEllipse(self, rect: QRectF) -> None: ...
    def drawEllipse(self, center: QPointF, rx: float, ry: float) -> None: ...
    def drawEllipse(self, x: float, y: float, w: float, h: float) -> None: ...
    def drawArc(self, rect: QRectF, startAngle: int, spanAngle: int) -> None: ...
    def drawPie(self, rect: QRectF, startAngle: int, spanAngle: int) -> None: ...
    def drawChord(self, rect: QRectF, startAngle: int, spanAngle: int) -> None: ...
    def drawRoundedRect(
        self, rect: QRectF, xRadius: float, yRadius: float, mode: Qt.SizeMode = ...
    ) -> None: ...
    def drawText(self, p: QPointF, text: str) -> None: ...
    def drawText(self, x: float, y: float, text: str) -> None: ...
    def drawText(self, rect: QRectF, flags: int, text: str) -> None: ...
    def drawText(
        self, rect: QRectF, flags: int, text: str, boundingRect: QRectF
    ) -> QRectF: ...
    def drawPixmap(self, p: QPointF, pm: QPixmap) -> None: ...
    def drawPixmap(self, x: float, y: float, pm: QPixmap) -> None: ...
    def drawPixmap(self, rect: QRectF, pm: QPixmap) -> None: ...
    def drawPixmap(
        self, x: float, y: float, w: float, h: float, pm: QPixmap
    ) -> None: ...
    def drawImage(self, p: QPointF, image: QImage) -> None: ...
    def drawImage(self, x: float, y: float, image: QImage) -> None: ...
    def drawImage(self, rect: QRectF, image: QImage) -> None: ...
    def fillRect(self, rect: QRectF, color: QColor) -> None: ...
    def fillRect(
        self, x: float, y: float, w: float, h: float, color: QColor
    ) -> None: ...
    def eraseRect(self, rect: QRectF) -> None: ...
    def eraseRect(self, x: float, y: float, w: float, h: float) -> None: ...
    def setRenderHint(self, hint: "RenderHint", on: bool = True) -> None: ...
    def renderHints(self) -> "RenderHint": ...
    def setRenderHints(self, hints: "RenderHint") -> None: ...
    def setClipRect(self, rect: QRectF, operation: Qt.ClipOperation = ...) -> None: ...
    def setClipRegion(
        self, region: "QRegion", operation: Qt.ClipOperation = ...
    ) -> None: ...
    def resetTransform(self) -> None: ...
    def translate(self, dx: float, dy: float) -> None: ...
    def scale(self, sx: float, sy: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def shear(self, sh: float, sv: float) -> None: ...
    def transform(self) -> "QTransform": ...
    def setTransform(self, transform: "QTransform", combine: bool = False) -> None: ...
    def worldTransform(self) -> "QTransform": ...

    class RenderHint:
        Antialiasing: int = ...
        TextAntialiasing: int = ...
        SmoothPixmapTransform: int = ...
        HighQualityAntialiasing: int = ...
        NonCosmeticDefaultPen: int = ...
        Qt4CompatiblePainting: int = ...
        LosslessImageRendering: int = ...

class QPen:
    def __init__(self) -> None: ...
    def __init__(self, color: QColor) -> None: ...
    def __init__(
        self,
        brush: QBrush,
        width: float = 0,
        style: Qt.PenStyle = ...,
        capStyle: Qt.PenCapStyle = ...,
        joinStyle: Qt.PenJoinStyle = ...,
    ) -> None: ...
    def style(self) -> Qt.PenStyle: ...
    def setStyle(self, style: Qt.PenStyle) -> None: ...
    def width(self) -> float: ...
    def setWidth(self, width: float) -> None: ...
    def color(self) -> QColor: ...
    def setColor(self, color: QColor) -> None: ...
    def brush(self) -> QBrush: ...
    def setBrush(self, brush: QBrush) -> None: ...
    def capStyle(self) -> Qt.PenCapStyle: ...
    def setCapStyle(self, style: Qt.PenCapStyle) -> None: ...
    def joinStyle(self) -> Qt.PenJoinStyle: ...
    def setJoinStyle(self, style: Qt.PenJoinStyle) -> None: ...
    def isCosmetic(self) -> bool: ...
    def setCosmetic(self, cosmetic: bool) -> None: ...
    def dashPattern(self) -> List[float]: ...
    def setDashPattern(self, pattern: List[float]) -> None: ...
    def dashOffset(self) -> float: ...
    def setDashOffset(self, offset: float) -> None: ...

class QTransform:
    def __init__(self) -> None: ...
    def __init__(
        self,
        h11: float,
        h12: float,
        h13: float,
        h21: float,
        h22: float,
        h23: float,
        h31: float,
        h32: float,
        h33: float,
    ) -> None: ...
    def __init__(self, other: "QTransform") -> None: ...
    def isIdentity(self) -> bool: ...
    def isInvertible(self) -> bool: ...
    def determinant(self) -> float: ...
    def map(self, p: QPointF) -> QPointF: ...
    def map(self, x: float, y: float) -> QPointF: ...
    def mapRect(self, rect: QRectF) -> QRectF: ...
    def mapPolygon(self, polygon: "QPolygonF") -> "QPolygonF": ...
    def reset(self) -> None: ...
    def translate(self, dx: float, dy: float) -> None: ...
    def scale(self, sx: float, sy: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def shear(self, sh: float, sv: float) -> None: ...
    def inverted(self) -> Tuple[bool, "QTransform"]: ...

class QPointF:
    def __init__(self) -> None: ...
    def __init__(self, xpos: float, ypos: float) -> None: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def setX(self, x: float) -> None: ...
    def setY(self, y: float) -> None: ...
    def isNull(self) -> bool: ...
    def manhattanLength(self) -> float: ...
    def __add__(self, other: QPointF) -> QPointF: ...
    def __sub__(self, other: QPointF) -> QPointF: ...
    def __mul__(self, factor: float) -> QPointF: ...
    def __div__(self, factor: float) -> QPointF: ...
    def toPoint(self) -> QPoint: ...

class QRectF:
    def __init__(self) -> None: ...
    def __init__(self, topLeft: QPointF, bottomRight: QPointF) -> None: ...
    def __init__(self, x: float, y: float, w: float, h: float) -> None: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def left(self) -> float: ...
    def right(self) -> float: ...
    def top(self) -> float: ...
    def bottom(self) -> float: ...
    def topLeft(self) -> QPointF: ...
    def bottomRight(self) -> QPointF: ...
    def topRight(self) -> QPointF: ...
    def bottomLeft(self) -> QPointF: ...
    def center(self) -> QPointF: ...
    def setX(self, x: float) -> None: ...
    def setY(self, y: float) -> None: ...
    def setWidth(self, w: float) -> None: ...
    def setHeight(self, h: float) -> None: ...
    def setLeft(self, left: float) -> None: ...
    def setRight(self, right: float) -> None: ...
    def setTop(self, top: float) -> None: ...
    def setBottom(self, bottom: float) -> None: ...
    def setTopLeft(self, p: QPointF) -> None: ...
    def setBottomRight(self, p: QPointF) -> None: ...
    def setTopRight(self, p: QPointF) -> None: ...
    def setBottomLeft(self, p: QPointF) -> None: ...
    def setRect(self, x: float, y: float, w: float, h: float) -> None: ...
    def getRect(self) -> Tuple[float, float, float, float]: ...
    def setCoords(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def getCoords(self) -> Tuple[float, float, float, float]: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isValid(self) -> bool: ...
    def contains(self, p: QPointF) -> bool: ...
    def contains(self, r: QRectF) -> bool: ...
    def contains(self, x: float, y: float) -> bool: ...
    def unite(self, other: QRectF) -> QRectF: ...
    def intersect(self, other: QRectF) -> QRectF: ...
    def intersects(self, other: QRectF) -> bool: ...
    def normalized(self) -> QRectF: ...
    def toRect(self) -> QRect: ...
    def toAlignedRect(self) -> QRect: ...

class QLineF:
    def __init__(self) -> None: ...
    def __init__(self, pt1: QPointF, pt2: QPointF) -> None: ...
    def __init__(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def p1(self) -> QPointF: ...
    def p2(self) -> QPointF: ...
    def x1(self) -> float: ...
    def y1(self) -> float: ...
    def x2(self) -> float: ...
    def y2(self) -> float: ...
    def dx(self) -> float: ...
    def dy(self) -> float: ...
    def length(self) -> float: ...
    def angle(self) -> float: ...
    def setP1(self, p1: QPointF) -> None: ...
    def setP2(self, p2: QPointF) -> None: ...
    def setPoints(self, p1: QPointF, p2: QPointF) -> None: ...
    def setLine(self, x1: float, y1: float, x2: float, y2: float) -> None: ...
    def isNull(self) -> bool: ...
    def unitVector(self) -> "QLineF": ...
    def normalVector(self) -> "QLineF": ...
    def intersect(
        self, line: "QLineF", intersectionPoint: QPointF
    ) -> "IntersectType": ...
    def angleTo(self, line: "QLineF") -> float: ...

    class IntersectType:
        NoIntersection: int = ...
        BoundedIntersection: int = ...
        UnboundedIntersection: int = ...

class QPolygonF:
    def __init__(self) -> None: ...
    def __init__(self, point: QPointF) -> None: ...
    def __init__(self, points: List[QPointF]) -> None: ...
    def __init__(self, rect: QRectF) -> None: ...
    def append(self, point: QPointF) -> None: ...
    def count(self) -> int: ...
    def __len__(self) -> int: ...
    def isClosed(self) -> bool: ...
    def boundingRect(self) -> QRectF: ...
    def containsPoint(self, point: QPointF, fillRule: Qt.FillRule) -> bool: ...
    def translate(self, offset: QPointF) -> None: ...
    def translate(self, dx: float, dy: float) -> None: ...
    def translated(self, offset: QPointF) -> "QPolygonF": ...
    def translated(self, dx: float, dy: float) -> "QPolygonF": ...

class QRegion:
    def __init__(self) -> None: ...
    def __init__(self, r: QRect) -> None: ...
    def __init__(self, region: "QRegion") -> None: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def rectCount(self) -> int: ...
    def rect(self, index: int) -> QRect: ...
    def boundingRect(self) -> QRect: ...
    def contains(self, p: QPoint) -> bool: ...
    def contains(self, r: QRect) -> bool: ...
    def intersects(self, r: QRect) -> bool: ...
    def translate(self, dx: int, dy: int) -> None: ...
    def translated(self, dx: int, dy: int) -> "QRegion": ...
    def united(self, r: "QRegion") -> "QRegion": ...
    def intersected(self, r: "QRegion") -> "QRegion": ...
    def subtracted(self, r: "QRegion") -> "QRegion": ...
    def xor(self, r: "QRegion") -> "QRegion": ...

class QPaintDevice:
    def __init__(self) -> None: ...
    def devType(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def widthMM(self) -> int: ...
    def heightMM(self) -> int: ...
    def logicalDpiX(self) -> int: ...
    def logicalDpiY(self) -> int: ...
    def physicalDpiX(self) -> int: ...
    def physicalDpiY(self) -> int: ...
    def colorCount(self) -> int: ...
    def depth(self) -> int: ...
    def paintingActive(self) -> bool: ...

class QEnterEvent(QEvent):
    def __init__(
        self, localPos: QPointF, windowPos: QPointF, screenPos: QPointF
    ) -> None: ...
    def localPos(self) -> QPointF: ...
    def windowPos(self) -> QPointF: ...
    def screenPos(self) -> QPointF: ...
    def pos(self) -> QPointF: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def globalPos(self) -> QPointF: ...
    def globalX(self) -> float: ...
    def globalY(self) -> float: ...

class QMouseEvent(QEvent):
    def __init__(
        self,
        type: QEvent.Type,
        localPos: QPointF,
        windowPos: QPointF,
        screenPos: QPointF,
        button: Qt.MouseButton,
        buttons: Qt.MouseButton,
        modifiers: Qt.KeyboardModifier,
    ) -> None: ...
    def localPos(self) -> QPointF: ...
    def windowPos(self) -> QPointF: ...
    def screenPos(self) -> QPointF: ...
    def pos(self) -> QPointF: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def globalPos(self) -> QPointF: ...
    def globalX(self) -> float: ...
    def globalY(self) -> float: ...
    def button(self) -> Qt.MouseButton: ...
    def buttons(self) -> Qt.MouseButton: ...
    def modifiers(self) -> Qt.KeyboardModifier: ...
    def source(self) -> "MouseEventSource": ...
    def flags(self) -> "MouseEventFlag": ...

    class MouseEventSource:
        MouseEventNotSynthesized: int = ...
        MouseEventSynthesizedBySystem: int = ...
        MouseEventSynthesizedByQt: int = ...
        MouseEventSynthesizedByApplication: int = ...

    class MouseEventFlag:
        MouseEventCreatedDoubleClick: int = ...

class QKeyEvent(QEvent):
    def __init__(
        self,
        type: QEvent.Type,
        key: int,
        modifiers: Qt.KeyboardModifier,
        text: str = ...,
        autorep: bool = False,
        count: int = 0,
    ) -> None: ...
    def key(self) -> int: ...
    def modifiers(self) -> Qt.KeyboardModifier: ...
    def text(self) -> str: ...
    def isAutoRepeat(self) -> bool: ...
    def count(self) -> int: ...
    def matches(self, key: QKeySequence.StandardKey) -> bool: ...
    def nativeScanCode(self) -> int: ...
    def nativeVirtualKey(self) -> int: ...
    def nativeModifiers(self) -> int: ...

class QFocusEvent(QEvent):
    def __init__(self, type: QEvent.Type) -> None: ...
    def gotFocus(self) -> bool: ...
    def lostFocus(self) -> bool: ...
    def reason(self) -> "Reason": ...

    class Reason:
        Mouse: int = ...
        Tab: int = ...
        Backtab: int = ...
        ActiveWindow: int = ...
        Popup: int = ...
        Shortcut: int = ...
        Menu: int = ...
        Other: int = ...

class QResizeEvent(QEvent):
    def __init__(self, size: QSize, oldSize: QSize) -> None: ...
    def size(self) -> QSize: ...
    def oldSize(self) -> QSize: ...

class QMoveEvent(QEvent):
    def __init__(self, pos: QPoint, oldPos: QPoint) -> None: ...
    def pos(self) -> QPoint: ...
    def oldPos(self) -> QPoint: ...

class QCloseEvent(QEvent):
    def __init__(self) -> None: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...

class QShowEvent(QEvent):
    def __init__(self) -> None: ...

class QHideEvent(QEvent):
    def __init__(self) -> None: ...

class QDragEnterEvent(QEvent):
    def __init__(
        self,
        pos: QPointF,
        actions: Qt.DropAction,
        data: Any,
        buttons: Qt.MouseButton,
        modifiers: Qt.KeyboardModifier,
    ) -> None: ...
    def pos(self) -> QPointF: ...
    def mousePos(self) -> QPointF: ...
    def possibleActions(self) -> Qt.DropAction: ...
    def proposedAction(self) -> Qt.DropAction: ...
    def dropAction(self) -> Qt.DropAction: ...
    def setDropAction(self, action: Qt.DropAction) -> None: ...
    def keyboardModifiers(self) -> Qt.KeyboardModifier: ...
    def mouseButtons(self) -> Qt.MouseButton: ...
    def mimeData(self) -> Any: ...
    def acceptProposedAction(self) -> None: ...

class QDragMoveEvent(QEvent):
    def __init__(
        self,
        pos: QPointF,
        actions: Qt.DropAction,
        data: Any,
        buttons: Qt.MouseButton,
        modifiers: Qt.KeyboardModifier,
    ) -> None: ...
    def pos(self) -> QPointF: ...
    def mousePos(self) -> QPointF: ...
    def possibleActions(self) -> Qt.DropAction: ...
    def proposedAction(self) -> Qt.DropAction: ...
    def dropAction(self) -> Qt.DropAction: ...
    def setDropAction(self, action: Qt.DropAction) -> None: ...
    def keyboardModifiers(self) -> Qt.KeyboardModifier: ...
    def mouseButtons(self) -> Qt.MouseButton: ...
    def mimeData(self) -> Any: ...
    def acceptProposedAction(self) -> None: ...

class QDropEvent(QEvent):
    def __init__(
        self,
        pos: QPointF,
        actions: Qt.DropAction,
        data: Any,
        buttons: Qt.MouseButton,
        modifiers: Qt.KeyboardModifier,
    ) -> None: ...
    def pos(self) -> QPointF: ...
    def mousePos(self) -> QPointF: ...
    def possibleActions(self) -> Qt.DropAction: ...
    def proposedAction(self) -> Qt.DropAction: ...
    def dropAction(self) -> Qt.DropAction: ...
    def setDropAction(self, action: Qt.DropAction) -> None: ...
    def keyboardModifiers(self) -> Qt.KeyboardModifier: ...
    def mouseButtons(self) -> Qt.MouseButton: ...
    def mimeData(self) -> Any: ...
    def acceptProposedAction(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...

class QDragLeaveEvent(QEvent):
    def __init__(self) -> None: ...

class QWheelEvent(QEvent):
    def __init__(
        self,
        pos: QPointF,
        globalPos: QPointF,
        pixelDelta: QPoint,
        angleDelta: QPoint,
        buttons: Qt.MouseButton,
        modifiers: Qt.KeyboardModifier,
        phase: "ScrollPhase",
        inverted: bool,
    ) -> None: ...
    def pos(self) -> QPointF: ...
    def globalPos(self) -> QPointF: ...
    def pixelDelta(self) -> QPoint: ...
    def angleDelta(self) -> QPoint: ...
    def buttons(self) -> Qt.MouseButton: ...
    def modifiers(self) -> Qt.KeyboardModifier: ...
    def phase(self) -> "ScrollPhase": ...
    def inverted(self) -> bool: ...
    def isAccepted(self) -> bool: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...

    class ScrollPhase:
        NoScrollPhase: int = ...
        ScrollBegin: int = ...
        ScrollUpdate: int = ...
        ScrollEnd: int = ...
        ScrollMomentum: int = ...

# Extend Qt class with additional enums
class Qt:
    class AspectRatioMode:
        IgnoreAspectRatio: int = ...
        KeepAspectRatio: int = ...
        KeepAspectRatioByExpanding: int = ...

    class TransformationMode:
        FastTransformation: int = ...
        SmoothTransformation: int = ...

    class BGMode:
        OpaqueMode: int = ...
        TransparentMode: int = ...

    class PenStyle:
        NoPen: int = ...
        SolidLine: int = ...
        DashLine: int = ...
        DotLine: int = ...
        DashDotLine: int = ...
        DashDotDotLine: int = ...
        CustomDashLine: int = ...

    class PenCapStyle:
        FlatCap: int = ...
        SquareCap: int = ...
        RoundCap: int = ...

    class PenJoinStyle:
        MiterJoin: int = ...
        BevelJoin: int = ...
        RoundJoin: int = ...
        SvgMiterJoin: int = ...

    class FillRule:
        OddEvenFill: int = ...
        WindingFill: int = ...

    class SizeMode:
        AbsoluteSize: int = ...
        RelativeSize: int = ...

    class ClipOperation:
        NoClip: int = ...
        ReplaceClip: int = ...
        IntersectClip: int = ...
        UniteClip: int = ...

    class CursorShape:
        ArrowCursor: int = ...
        UpArrowCursor: int = ...
        CrossCursor: int = ...
        WaitCursor: int = ...
        IBeamCursor: int = ...
        SizeVerCursor: int = ...
        SizeHorCursor: int = ...
        SizeBDiagCursor: int = ...
        SizeFDiagCursor: int = ...
        SizeAllCursor: int = ...
        BlankCursor: int = ...
        SplitVCursor: int = ...
        SplitHCursor: int = ...
        PointingHandCursor: int = ...
        ForbiddenCursor: int = ...
        WhatsThisCursor: int = ...
        BusyCursor: int = ...
        OpenHandCursor: int = ...
        ClosedHandCursor: int = ...
        DragCopyCursor: int = ...
        DragMoveCursor: int = ...
        DragLinkCursor: int = ...
        BitmapCursor: int = ...

    class MouseButton:
        NoButton: int = ...
        LeftButton: int = ...
        RightButton: int = ...
        MiddleButton: int = ...

    class DropAction:
        CopyAction: int = ...
        MoveAction: int = ...
        LinkAction: int = ...
        ActionMask: int = ...
        IgnoreAction: int = ...
        TargetMoveAction: int = ...

    class BrushStyle:
        NoBrush: int = ...
        SolidPattern: int = ...
        Dense1Pattern: int = ...
        Dense2Pattern: int = ...
        Dense3Pattern: int = ...
        Dense4Pattern: int = ...
        Dense5Pattern: int = ...
        Dense6Pattern: int = ...
        Dense7Pattern: int = ...
        HorPattern: int = ...
        VerPattern: int = ...
        CrossPattern: int = ...
        BDiagPattern: int = ...
        FDiagPattern: int = ...
        DiagCrossPattern: int = ...
        LinearGradientPattern: int = ...
        RadialGradientPattern: int = ...
        ConicalGradientPattern: int = ...
        TexturePattern: int = ...

    class GlobalColor:
        color0: int = ...
        color1: int = ...
        black: int = ...
        white: int = ...
        darkGray: int = ...
        gray: int = ...
        lightGray: int = ...
        red: int = ...
        green: int = ...
        blue: int = ...
        cyan: int = ...
        magenta: int = ...
        yellow: int = ...
        darkRed: int = ...
        darkGreen: int = ...
        darkBlue: int = ...
        darkCyan: int = ...
        darkMagenta: int = ...
        darkYellow: int = ...
        transparent: int = ...

# Add QMenu import for QAction
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from PySide6.QtWidgets import QMenu
