"""
Type stubs for PySide6.QtWebEngineWidgets
Generated for modorganizer-linux project
"""

from typing import Optional, Any
from PySide6.QtWidgets import QWidget
from PySide6.QtCore import QObject, QUrl, QSize, QRect, QPoint
from PySide6.QtGui import QColor

class QWebEngineView(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def load(self, url: QUrl) -> None: ...
    def load(self, request: "QWebEngineHttpRequest") -> None: ...
    def setHtml(self, html: str, baseUrl: QUrl = ...) -> None: ...
    def setContent(
        self, data: bytes, mimeType: str = ..., baseUrl: QUrl = ...
    ) -> None: ...
    def url(self) -> QUrl: ...
    def title(self) -> str: ...
    def icon(self) -> Any: ...
    def selectedText(self) -> str: ...
    def hasSelection(self) -> bool: ...
    def page(self) -> "QWebEnginePage": ...
    def setPage(self, page: "QWebEnginePage") -> None: ...
    def history(self) -> "QWebEngineHistory": ...
    def settings(self) -> "QWebEngineSettings": ...
    def pageAction(self, action: "WebAction") -> Any: ...
    def triggerPageAction(self, action: "WebAction", checked: bool = False) -> None: ...
    def isRenderingEnabled(self) -> bool: ...
    def setRenderProcessEnabled(self, enabled: bool) -> None: ...
    def zoomFactor(self) -> float: ...
    def setZoomFactor(self, factor: float) -> None: ...
    def findText(
        self, subString: str, options: "QWebEnginePage.FindFlags" = ...
    ) -> Any: ...
    def stop(self) -> None: ...
    def back(self) -> None: ...
    def forward(self) -> None: ...
    def reload(self) -> None: ...
    def reloadAndBypassCache(self) -> None: ...

    class WebAction:
        NoWebAction: int = ...
        Back: int = ...
        Forward: int = ...
        Stop: int = ...
        Reload: int = ...
        ReloadAndBypassCache: int = ...
        Cut: int = ...
        Copy: int = ...
        Paste: int = ...
        Undo: int = ...
        Redo: int = ...
        SelectAll: int = ...
        PasteAndMatchStyle: int = ...
        OpenLinkInThisWindow: int = ...
        OpenLinkInNewWindow: int = ...
        OpenLinkInNewTab: int = ...
        OpenLinkInNewBackgroundTab: int = ...
        CopyLinkToClipboard: int = ...
        CopyImageToClipboard: int = ...
        CopyImageUrlToClipboard: int = ...
        CopyMediaUrlToClipboard: int = ...
        ToggleMediaControls: int = ...
        ToggleMediaLoop: int = ...
        ToggleMediaPlayPause: int = ...
        ToggleMediaMute: int = ...
        DownloadLinkToDisk: int = ...
        DownloadImageToDisk: int = ...
        DownloadMediaToDisk: int = ...
        InspectElement: int = ...
        ExitFullScreen: int = ...
        RequestClose: int = ...
        Unselect: int = ...
        SavePage: int = ...
        ViewSource: int = ...

class QWebEnginePage(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def view(self) -> QWebEngineView: ...
    def setView(self, view: QWebEngineView) -> None: ...
    def profile(self) -> "QWebEngineProfile": ...
    def setUrl(self, url: QUrl) -> None: ...
    def url(self) -> QUrl: ...
    def title(self) -> str: ...
    def requestedUrl(self) -> QUrl: ...
    def icon(self) -> Any: ...
    def hasSelection(self) -> bool: ...
    def selectedText(self) -> str: ...
    def viewSource(self) -> None: ...
    def toHtml(self, callable: Any) -> None: ...
    def toPlainText(self, callable: Any) -> None: ...
    def content(self) -> Any: ...
    def setHtml(self, html: str, baseUrl: QUrl = ...) -> None: ...
    def setContent(
        self, data: bytes, mimeType: str = ..., baseUrl: QUrl = ...
    ) -> None: ...
    def load(self, url: QUrl) -> None: ...
    def load(self, request: "QWebEngineHttpRequest") -> None: ...
    def history(self) -> "QWebEngineHistory": ...
    def settings(self) -> "QWebEngineSettings": ...
    def scripts(self) -> "QWebEngineScriptCollection": ...
    def runJavaScript(self, scriptSource: str, worldId: int = ...) -> None: ...
    def runJavaScript(self, scriptSource: str, resultCallback: Any) -> None: ...
    def runJavaScript(
        self, scriptSource: str, worldId: int, resultCallback: Any
    ) -> None: ...
    def print(self, printer: Any) -> None: ...
    def printToPdf(self, filePath: str) -> None: ...
    def printToPdf(self, callable: Any) -> None: ...
    def executeJavaScript(self, scriptSource: str) -> None: ...
    def findText(
        self, subString: str, options: "FindFlags" = ..., callback: Any = ...
    ) -> None: ...
    def stop(self) -> None: ...
    def back(self) -> None: ...
    def forward(self) -> None: ...
    def reload(self) -> None: ...
    def reloadAndBypassCache(self) -> None: ...
    def triggerAction(
        self, action: QWebEngineView.WebAction, checked: bool = False
    ) -> None: ...
    def setAudioMuted(self, muted: bool) -> None: ...
    def isAudioMuted(self) -> bool: ...
    def setWebChannel(self, channel: Any) -> None: ...
    def webChannel(self) -> Any: ...
    def setBackgroundColor(self, color: QColor) -> None: ...
    def backgroundColor(self) -> QColor: ...
    def featurePermissionRequested(
        self, securityOrigin: "QWebEngineSecurityOrigin", feature: "Feature"
    ) -> None: ...
    def certificates(self) -> Any: ...
    def setCertificate(self, certificate: Any) -> None: ...
    def setLifecycleState(self, state: "LifecycleState") -> None: ...
    def lifecycleState(self) -> "LifecycleState": ...
    def recommendedState(self) -> "LifecycleState": ...

    class FindFlag:
        FindBackward: int = ...
        FindCaseSensitively: int = ...

    class FindFlags: ...

    class Feature:
        Geolocation: int = ...
        MediaAudioCapture: int = ...
        MediaVideoCapture: int = ...
        MediaAudioVideoCapture: int = ...
        MouseLock: int = ...
        DesktopVideoCapture: int = ...
        DesktopAudioVideoCapture: int = ...

    class LifecycleState:
        Active: int = ...
        Frozen: int = ...
        Discarded: int = ...

class QWebEngineProfile(QObject):
    def __init__(self, name: str, parent: Optional[QObject] = None) -> None: ...
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    @staticmethod
    def defaultProfile() -> "QWebEngineProfile": ...
    def storageName(self) -> str: ...
    def isOffTheRecord(self) -> bool: ...
    def persistentCookiesPolicy(self) -> "PersistentCookiesPolicy": ...
    def setPersistentCookiesPolicy(self, policy: "PersistentCookiesPolicy") -> None: ...
    def cachePath(self) -> str: ...
    def setCachePath(self, path: str) -> None: ...
    def persistentStoragePath(self) -> str: ...
    def setPersistentStoragePath(self, path: str) -> None: ...
    def httpCacheType(self) -> "HttpCacheType": ...
    def setHttpCacheType(self, type: "HttpCacheType") -> None: ...
    def httpCacheMaximumSize(self) -> int: ...
    def setHttpCacheMaximumSize(self, size: int) -> None: ...
    def userAgent(self) -> str: ...
    def setUserAgent(self, userAgent: str) -> None: ...
    def spellCheckEnabled(self) -> bool: ...
    def setSpellCheckEnabled(self, enabled: bool) -> None: ...
    def spellCheckLanguages(self) -> List[str]: ...
    def setSpellCheckLanguages(self, languages: List[str]) -> None: ...
    def settings(self) -> "QWebEngineSettings": ...
    def scripts(self) -> "QWebEngineScriptCollection": ...
    def urlSchemeHandler(
        self, scheme: str
    ) -> Optional["QWebEngineUrlSchemeHandler"]: ...
    def installUrlSchemeHandler(
        self, scheme: str, handler: "QWebEngineUrlSchemeHandler"
    ) -> None: ...
    def removeUrlSchemeHandler(self, scheme: str) -> None: ...
    def cookieStore(self) -> "QWebEngineCookieStore": ...
    def downloadPath(self) -> str: ...
    def setDownloadPath(self, path: str) -> None: ...
    def downloadRequested(self, download: "QWebEngineDownloadItem") -> None: ...

    class PersistentCookiesPolicy:
        NoPersistentCookies: int = ...
        AllowPersistentCookies: int = ...
        ForcePersistentCookies: int = ...

    class HttpCacheType:
        MemoryHttpCache: int = ...
        DiskHttpCache: int = ...
        NoCache: int = ...

class QWebEngineSettings:
    def __init__(self) -> None: ...
    def defaultSettings(self) -> "QWebEngineSettings": ...
    def setAttribute(self, attr: "WebAttribute", on: bool) -> None: ...
    def testAttribute(self, attr: "WebAttribute") -> bool: ...
    def resetAttribute(self, attr: "WebAttribute") -> None: ...
    def setFontFamily(self, which: "FontFamily", family: str) -> None: ...
    def fontFamily(self, which: "FontFamily") -> str: ...
    def setFontSize(self, type: "FontSize", size: int) -> None: ...
    def fontSize(self, type: "FontSize") -> int: ...
    def resetFontFamily(self, which: "FontFamily") -> None: ...
    def resetFontSize(self, type: "FontSize") -> None: ...
    def setDefaultTextEncoding(self, encoding: str) -> None: ...
    def defaultTextEncoding(self) -> str: ...

    class WebAttribute:
        AutoLoadImages: int = ...
        JavascriptEnabled: int = ...
        JavascriptCanOpenWindows: int = ...
        JavascriptCanAccessClipboard: int = ...
        LinksIncludedInFocusChain: int = ...
        LocalContentCanAccessRemoteUrls: int = ...
        LocalContentCanAccessFileUrls: int = ...
        SpatialNavigationEnabled: int = ...
        LocalContentCanAccessFileUrls: int = ...
        HyperlinkAuditingEnabled: int = ...
        ScrollAnimatorEnabled: int = ...
        ErrorPageEnabled: int = ...
        PluginsEnabled: int = ...
        FullScreenSupportEnabled: int = ...
        ScreenCaptureEnabled: int = ...
        WebGLEnabled: int = ...
        Accelerated2dCanvasEnabled: int = ...
        AutoLoadIconsForPage: int = ...
        TouchIconsEnabled: int = ...
        FocusOnNavigationEnabled: int = ...
        PrintElementBackgrounds: int = ...
        AllowRunningInsecureContent: int = ...
        AllowGeolocationInsecureOrigins: int = ...
        AllowWindowActivationFromJavaScript: int = ...
        ShowScrollBars: int = ...
        PlayRequiresUserGesture: int = ...
        JavascriptCanPaste: int = ...
        WebRTCPublicInterfacesOnly: int = ...
        DnsPrefetchEnabled: int = ...

    class FontFamily:
        StandardFont: int = ...
        FixedFont: int = ...
        SerifFont: int = ...
        SansSerifFont: int = ...
        CursiveFont: int = ...
        FantasyFont: int = ...

    class FontSize:
        MinimumFontSize: int = ...
        MinimumLogicalFontSize: int = ...
        DefaultFontSize: int = ...
        DefaultFixedFontSize: int = ...

class QWebEngineHistory:
    def __init__(self) -> None: ...
    def backItems(self, maxItems: int = ...) -> List["QWebEngineHistoryItem"]: ...
    def forwardItems(self, maxItems: int = ...) -> List["QWebEngineHistoryItem"]: ...
    def items(self) -> List["QWebEngineHistoryItem"]: ...
    def currentItem(self) -> "QWebEngineHistoryItem": ...
    def currentItemIndex(self) -> int: ...
    def backItem(self) -> "QWebEngineHistoryItem": ...
    def forwardItem(self) -> "QWebEngineHistoryItem": ...
    def canGoBack(self) -> bool: ...
    def canGoForward(self) -> bool: ...
    def goBack(self) -> None: ...
    def goForward(self) -> None: ...
    def goToItem(self, item: "QWebEngineHistoryItem") -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...

class QWebEngineHistoryItem:
    def __init__(self, other: "QWebEngineHistoryItem") -> None: ...
    def url(self) -> QUrl: ...
    def title(self) -> str: ...
    def lastVisited(self) -> Any: ...
    def icon(self) -> Any: ...
    def isValid(self) -> bool: ...

class QWebEngineScript:
    def __init__(self) -> None: ...
    def __init__(self, other: "QWebEngineScript") -> None: ...
    def name(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def sourceCode(self) -> str: ...
    def setSourceCode(self, sourceCode: str) -> None: ...
    def injectionPoint(self) -> "InjectionPoint": ...
    def setInjectionPoint(self, point: "InjectionPoint") -> None: ...
    def runsOnSubFrames(self) -> bool: ...
    def setRunsOnSubFrames(self, on: bool) -> None: ...
    def worldId(self) -> int: ...
    def setWorldId(self, worldId: int) -> None: ...
    def sourceUrl(self) -> QUrl: ...
    def setSourceUrl(self, url: QUrl) -> None: ...

    class InjectionPoint:
        DocumentCreation: int = ...
        DocumentReady: int = ...
        Deferred: int = ...

class QWebEngineScriptCollection:
    def __init__(self) -> None: ...
    def __init__(self, other: "QWebEngineScriptCollection") -> None: ...
    def count(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def contains(self, value: QWebEngineScript) -> bool: ...
    def __contains__(self, value: QWebEngineScript) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def find(self, name: str) -> List[QWebEngineScript]: ...
    def insert(self, script: QWebEngineScript) -> None: ...
    def insert(self, list: "QWebEngineScriptCollection") -> None: ...
    def remove(self, script: QWebEngineScript) -> None: ...
    def clear(self) -> None: ...
    def toList(self) -> List[QWebEngineScript]: ...

class QWebEngineDownloadItem(QObject):
    def __init__(self) -> None: ...
    def id(self) -> int: ...
    def url(self) -> QUrl: ...
    def path(self) -> str: ...
    def setPath(self, path: str) -> None: ...
    def isPaused(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def savePageFormat(self) -> "SavePageFormat": ...
    def mimeType(self) -> str: ...
    def receivedBytes(self) -> int: ...
    def totalBytes(self) -> int: ...
    def type(self) -> "DownloadType": ...
    def interruptReason(self) -> "DownloadInterruptReason": ...
    def page(self) -> QWebEnginePage: ...
    def accept(self) -> None: ...
    def cancel(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

    class DownloadType:
        Attachment: int = ...
        SavePage: int = ...
        UnknownType: int = ...

    class SavePageFormat:
        UnknownSaveFormat: int = ...
        SingleHtmlSaveFormat: int = ...
        CompleteHtmlSaveFormat: int = ...
        MimeTypeHtmlSaveFormat: int = ...

    class DownloadInterruptReason:
        NoReason: int = ...
        FileFailed: int = ...
        FileAccessDenied: int = ...
        FileNoSpace: int = ...
        FileNameTooLong: int = ...
        FileTooLarge: int = ...
        FileVirusInfected: int = ...
        FileTransientError: int = ...
        FileBlocked: int = ...
        SecurityCheckFailed: int = ...
        ServerError: int = ...
        ServerBadContent: int = ...
        ServerForbidden: int = ...
        ServerUnreachable: int = ...
        ServerContentLengthMismatch: int = ...
        ServerCrossOriginRedirect: int = ...
        UserCanceled: int = ...
        DownloadPaused: int = ...

class QWebEngineCookieStore(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def setCookie(
        self, cookie: Any, origin: Optional["QWebEngineSecurityOrigin"] = None
    ) -> None: ...
    def deleteCookie(self, cookie: Any) -> None: ...
    def deleteAllCookies(self) -> None: ...
    def loadAllCookies(self) -> None: ...
    def cookieAdded(self, cookie: Any) -> None: ...
    def cookieRemoved(self, cookie: Any) -> None: ...

class QWebEngineSecurityOrigin:
    def __init__(self, other: "QWebEngineSecurityOrigin") -> None: ...
    def scheme(self) -> str: ...
    def host(self) -> str: ...
    def port(self) -> int: ...
    def subdomain(self) -> str: ...
    def __lt__(self, other: "QWebEngineSecurityOrigin") -> bool: ...
    def __eq__(self, other: "QWebEngineSecurityOrigin") -> bool: ...

class QWebEngineUrlSchemeHandler(QObject):
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def requestStarted(self, request: "QWebEngineUrlRequestJob") -> None: ...

class QWebEngineUrlRequestJob(QObject):
    def __init__(self) -> None: ...
    def requestUrl(self) -> QUrl: ...
    def initiator(self) -> QUrl: ...
    def fail(self, error: int) -> None: ...
    def redirect(self, url: QUrl) -> None: ...
    def reply(self, httpStatusCode: int, headers: Any, data: Any) -> None: ...
    def reply(self, httpStatusCode: int, headers: Any, device: Any) -> None: ...

class QWebEngineHttpRequest:
    def __init__(self) -> None: ...
    def __init__(
        self, url: QUrl, method: "QWebEngineHttpRequest.Method" = ...
    ) -> None: ...
    def __init__(self, other: "QWebEngineHttpRequest") -> None: ...
    def url(self) -> QUrl: ...
    def setUrl(self, url: QUrl) -> None: ...
    def method(self) -> "QWebEngineHttpRequest.Method": ...
    def setMethod(self, method: "QWebEngineHttpRequest.Method") -> None: ...
    def hasHeader(self, name: bytes) -> bool: ...
    def header(self, name: bytes) -> bytes: ...
    def setHeader(self, name: bytes, value: bytes) -> None: ...
    def unsetHeader(self, name: bytes) -> None: ...
    def headers(self) -> Any: ...
    def setHeaders(self, headers: Any) -> None: ...
    def postData(self) -> bytes: ...
    def setPostData(self, postData: bytes) -> None: ...

    class Method:
        Get: int = ...
        Post: int = ...
        Put: int = ...
        Delete: int = ...
        Head: int = ...
        Unknown: int = ...

class QWebEngineFullScreenRequest:
    def __init__(self, other: "QWebEngineFullScreenRequest") -> None: ...
    def toggleOn(self) -> bool: ...
    def origin(self) -> QWebEngineSecurityOrigin: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
