"""
Type stubs for PySide6.QtWidgets
Generated for modorganizer-linux project
"""

from typing import Any, Callable, Optional, Union, List, Tuple
from PySide6.QtCore import Qt, QObject, QSize, QSizePolicy, QMetaObject, QPoint, QRect
from PySide6.QtGui import (
    QAction,
    QIcon,
    QPalette,
    QColor,
    QCursor,
    QFont,
    QKeySequence,
    QBrush,
)

class QWidget:
    def __init__(self, parent: Optional["QWidget"] = None) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def objectName(self) -> str: ...
    def setLayout(self, layout: "QLayout") -> None: ...
    def layout(self) -> Optional["QLayout"]: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def sizePolicy(self) -> QSizePolicy: ...
    def setSizePolicy(self, policy: QSizePolicy) -> None: ...
    def parent(self) -> Optional["QObject"]: ...
    def setParent(self, parent: "QWidget") -> None: ...
    def resize(self, w: int, h: int) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def pos(self) -> QPoint: ...
    def geometry(self) -> QRect: ...
    def setGeometry(self, x: int, y: int, w: int, h: int) -> None: ...
    def update(self) -> None: ...
    def repaint(self) -> None: ...
    def close(self) -> bool: ...
    def setFocus(self) -> None: ...
    def clearFocus(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...
    def styleSheet(self) -> str: ...

class QLayout:
    def __init__(self, parent: Optional["QWidget"] = None) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def objectName(self) -> str: ...
    def setContentsMargins(
        self, left: int, top: int, right: int, bottom: int
    ) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def addLayout(self, layout: "QLayout") -> None: ...
    def addItem(self, item: "QLayoutItem") -> None: ...
    def parentWidget(self) -> Optional[QWidget]: ...

class QLayoutItem:
    def __init__(self) -> None: ...
    def widget(self) -> Optional[QWidget]: ...
    def layout(self) -> Optional["QLayout"]: ...

class QVBoxLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def addLayout(self, layout: QLayout) -> None: ...
    def addSpacing(self, spacing: int) -> None: ...
    def addStretch(self, stretch: int = 0) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...

class QHBoxLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def addLayout(self, layout: QLayout) -> None: ...
    def addSpacing(self, spacing: int) -> None: ...
    def addStretch(self, stretch: int = 0) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...

class QGridLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(
        self,
        widget: QWidget,
        row: int,
        column: int,
        rowSpan: int = 1,
        columnSpan: int = 1,
    ) -> None: ...
    def addLayout(
        self,
        layout: QLayout,
        row: int,
        column: int,
        rowSpan: int = 1,
        columnSpan: int = 1,
    ) -> None: ...
    def setRowStretch(self, row: int, stretch: int) -> None: ...
    def setColumnStretch(self, column: int, stretch: int) -> None: ...

class QFormLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addRow(self, labelText: str, field: QWidget) -> None: ...
    def addRow(self, label: QWidget, field: QWidget) -> None: ...
    def addRow(self, widget: QWidget) -> None: ...
    def setLayout(self, row: int, role: "ItemRole", layout: QLayout) -> None: ...

    class ItemRole:
        FieldRole: int = ...
        LabelRole: int = ...

class QSpacerItem(QLayoutItem):
    def __init__(
        self,
        w: int,
        h: int,
        hData: QSizePolicy.Policy = ...,
        vData: QSizePolicy.Policy = ...,
    ) -> None: ...

class QApplication:
    def __init__(self, argv: List[str]) -> None: ...
    @staticmethod
    def instance() -> Optional["QApplication"]: ...
    @staticmethod
    def exec() -> int: ...
    @staticmethod
    def quit() -> None: ...
    @staticmethod
    def closeAllWindows() -> None: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...

class QMainWindow(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def centralWidget(self) -> Optional[QWidget]: ...
    def setMenuBar(self, menuBar: "QMenuBar") -> None: ...
    def menuBar(self) -> "QMenuBar": ...
    def setStatusBar(self, statusBar: "QStatusBar") -> None: ...
    def statusBar(self) -> "QStatusBar": ...
    def addToolBar(self, area: Qt.ToolBarArea, toolBar: "QToolBar") -> None: ...
    def addToolBar(self, toolBar: "QToolBar") -> None: ...
    def addDockWidget(
        self, area: Qt.DockWidgetArea, dockWidget: "QDockWidget"
    ) -> None: ...
    def removeDockWidget(self, dockWidget: "QDockWidget") -> None: ...

class QDialog(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def setResult(self, result: int) -> None: ...
    def result(self) -> int: ...

class QWizard(QDialog):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addPage(self, page: "QWizardPage") -> int: ...
    def setPage(self, id: int, page: "QWizardPage") -> None: ...
    def removePage(self, id: int) -> None: ...
    def currentPage(self) -> Optional["QWizardPage"]: ...
    def page(self, id: int) -> Optional["QWizardPage"]: ...
    def field(self, name: str) -> Any: ...
    def setField(self, name: str, value: Any) -> None: ...
    def restart(self) -> None: ...
    def next(self) -> None: ...
    def back(self) -> None: ...
    def accept(self) -> None: ...

class QWizardPage(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def setSubTitle(self, subTitle: str) -> None: ...
    def subTitle(self) -> str: ...
    def setPixmap(self, which: "WizardPixmap", pixmap: QPixmap) -> None: ...
    def registerField(
        self,
        name: str,
        widget: QWidget,
        property: Optional[str] = None,
        changedSignal: Optional[str] = None,
    ) -> None: ...
    def field(self, name: str) -> Any: ...
    def setField(self, name: str, value: Any) -> None: ...
    def initializePage(self) -> None: ...
    def cleanupPage(self) -> None: ...
    def validatePage(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def wizard(self) -> Optional[QWizard]: ...

    class WizardPixmap:
        LogoPixmap: int = ...
        WatermarkPixmap: int = ...
        BannerPixmap: int = ...
        BackgroundPixmap: int = ...

class QLabel(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPixmap(self, pixmap: QPixmap) -> None: ...
    def pixmap(self) -> Optional[QPixmap]: ...
    def setWordWrap(self, on: bool) -> None: ...
    def wordWrap(self) -> bool: ...
    def setAlignment(self, alignment: Qt.AlignmentFlag) -> None: ...
    def alignment(self) -> Qt.AlignmentFlag: ...
    def clear(self) -> None: ...
    def setTextFormat(self, format: Qt.TextFormat) -> None: ...
    def textFormat(self) -> Qt.TextFormat: ...

class QPushButton(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setDefault(self, isDefault: bool) -> None: ...
    def isDefault(self) -> bool: ...
    def setAutoDefault(self, isAutoDefault: bool) -> None: ...
    def autoDefault(self) -> bool: ...
    def click(self) -> None: ...
    def setMenu(self, menu: "QMenu") -> None: ...
    def menu(self) -> Optional["QMenu"]: ...

class QCheckBox(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def setTristate(self, y: bool = True) -> None: ...
    def isTristate(self) -> bool: ...
    def checkState(self) -> Qt.CheckState: ...
    def setCheckState(self, state: Qt.CheckState) -> None: ...

class QRadioButton(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def setAutoExclusive(self, autoExclusive: bool) -> None: ...
    def autoExclusive(self) -> bool: ...

class QLineEdit(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def clear(self) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def placeholderText(self) -> str: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def setMaxLength(self, maxLength: int) -> None: ...
    def maxLength(self) -> int: ...
    def setEchoMode(self, mode: "EchoMode") -> None: ...
    def echoMode(self) -> "EchoMode": ...
    def setCursorPosition(self, pos: int) -> None: ...
    def cursorPosition(self) -> int: ...
    def selectAll(self) -> None: ...
    def copy(self) -> None: ...
    def cut(self) -> None: ...
    def paste(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...

    class EchoMode:
        Normal: int = ...
        NoEcho: int = ...
        Password: int = ...
        PasswordEchoOnEdit: int = ...

class QTextEdit(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def toHtml(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def setHtml(self, html: str) -> None: ...
    def clear(self) -> None: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def append(self, text: str) -> None: ...
    def insertPlainText(self, text: str) -> None: ...

class QPlainTextEdit(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def clear(self) -> None: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def appendPlainText(self, text: str) -> None: ...
    def insertPlainText(self, text: str) -> None: ...

class QListWidget(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addItem(self, item: Union[str, "QListWidgetItem"]) -> None: ...
    def addItems(self, items: List[str]) -> None: ...
    def insertItem(self, row: int, item: Union[str, "QListWidgetItem"]) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentRow(self) -> int: ...
    def currentItem(self) -> Optional["QListWidgetItem"]: ...
    def setCurrentRow(self, row: int) -> None: ...
    def setCurrentItem(self, item: "QListWidgetItem") -> None: ...
    def item(self, row: int) -> Optional["QListWidgetItem"]: ...
    def takeItem(self, row: int) -> Optional["QListWidgetItem"]: ...
    def selectedItems(self) -> List["QListWidgetItem"]: ...
    def setSelectionMode(self, mode: "SelectionMode") -> None: ...
    def selectionMode(self) -> "SelectionMode": ...
    def setEditTriggers(self, triggers: "EditTrigger") -> None: ...
    def editTriggers(self) -> "EditTrigger": ...
    def setEnabled(self, enabled: bool) -> None: ...
    def currentText(self) -> str: ...

    class SelectionMode:
        SingleSelection: int = ...
        MultiSelection: int = ...
        ExtendedSelection: int = ...
        ContiguousSelection: int = ...
        NoSelection: int = ...

    class EditTrigger:
        NoEditTriggers: int = ...
        CurrentChanged: int = ...
        DoubleClicked: int = ...
        SelectedClicked: int = ...
        EditKeyPressed: int = ...
        AnyKeyPressed: int = ...
        AllEditTriggers: int = ...

class QListWidgetItem:
    def __init__(
        self, text: str = "", parent: Optional[QListWidget] = None
    ) -> None: ...
    def __init__(
        self, icon: QIcon, text: str = "", parent: Optional[QListWidget] = None
    ) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...
    def setFlags(self, flags: Qt.ItemFlag) -> None: ...
    def flags(self) -> Qt.ItemFlag: ...
    def setCheckState(self, state: Qt.CheckState) -> None: ...
    def checkState(self) -> Qt.CheckState: ...
    def listWidget(self) -> Optional[QListWidget]: ...
    def row(self) -> int: ...

class QTreeWidget(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addTopLevelItem(self, item: "QTreeWidgetItem") -> None: ...
    def addTopLevelItems(self, items: List["QTreeWidgetItem"]) -> None: ...
    def insertTopLevelItem(self, index: int, item: "QTreeWidgetItem") -> None: ...
    def clear(self) -> None: ...
    def topLevelItem(self, index: int) -> Optional["QTreeWidgetItem"]: ...
    def topLevelItemCount(self) -> int: ...
    def currentItem(self) -> Optional["QTreeWidgetItem"]: ...
    def setCurrentItem(self, item: "QTreeWidgetItem") -> None: ...
    def selectedItems(self) -> List["QTreeWidgetItem"]: ...
    def setHeaderLabels(self, labels: List[str]) -> None: ...
    def setColumnCount(self, columns: int) -> None: ...
    def columnCount(self) -> int: ...
    def setSelectionMode(self, mode: QAbstractItemView.SelectionMode) -> None: ...
    def selectionMode(self) -> QAbstractItemView.SelectionMode: ...
    def setEditTriggers(self, triggers: QAbstractItemView.EditTrigger) -> None: ...
    def editTriggers(self) -> QAbstractItemView.EditTrigger: ...

class QTreeWidgetItem:
    def __init__(self, parent: Optional[QTreeWidget] = None) -> None: ...
    def __init__(self, parent: Optional["QTreeWidgetItem"] = None) -> None: ...
    def __init__(
        self, strings: List[str], parent: Optional[QTreeWidget] = None
    ) -> None: ...
    def setText(self, column: int, text: str) -> None: ...
    def text(self, column: int) -> str: ...
    def setIcon(self, column: int, icon: QIcon) -> None: ...
    def icon(self, column: int) -> QIcon: ...
    def setData(self, column: int, role: int, value: Any) -> None: ...
    def data(self, column: int, role: int) -> Any: ...
    def setFlags(self, flags: Qt.ItemFlag) -> None: ...
    def flags(self) -> Qt.ItemFlag: ...
    def setCheckState(self, column: int, state: Qt.CheckState) -> None: ...
    def checkState(self, column: int) -> Qt.CheckState: ...
    def child(self, index: int) -> Optional["QTreeWidgetItem"]: ...
    def childCount(self) -> int: ...
    def addChild(self, child: "QTreeWidgetItem") -> None: ...
    def insertChild(self, index: int, child: "QTreeWidgetItem") -> None: ...
    def takeChild(self, index: int) -> Optional["QTreeWidgetItem"]: ...
    def parent(self) -> Optional["QTreeWidgetItem"]: ...
    def treeWidget(self) -> Optional[QTreeWidget]: ...

class QTableWidget(QWidget):
    def __init__(
        self, rows: int = 0, columns: int = 0, parent: Optional[QWidget] = None
    ) -> None: ...
    def setRowCount(self, rows: int) -> None: ...
    def setColumnCount(self, columns: int) -> None: ...
    def rowCount(self) -> int: ...
    def columnCount(self) -> int: ...
    def setItem(self, row: int, column: int, item: "QTableWidgetItem") -> None: ...
    def item(self, row: int, column: int) -> Optional["QTableWidgetItem"]: ...
    def takeItem(self, row: int, column: int) -> Optional["QTableWidgetItem"]: ...
    def clear(self) -> None: ...
    def setHorizontalHeaderLabels(self, labels: List[str]) -> None: ...
    def setVerticalHeaderLabels(self, labels: List[str]) -> None: ...
    def setSelectionMode(self, mode: QAbstractItemView.SelectionMode) -> None: ...
    def selectionMode(self) -> QAbstractItemView.SelectionMode: ...
    def selectedItems(self) -> List["QTableWidgetItem"]: ...
    def currentRow(self) -> int: ...
    def currentColumn(self) -> int: ...
    def currentItem(self) -> Optional["QTableWidgetItem"]: ...

class QTableWidgetItem:
    def __init__(self, text: str = "", type: int = 0) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...
    def setFlags(self, flags: Qt.ItemFlag) -> None: ...
    def flags(self) -> Qt.ItemFlag: ...
    def setCheckState(self, state: Qt.CheckState) -> None: ...
    def checkState(self) -> Qt.CheckState: ...
    def row(self) -> int: ...
    def column(self) -> int: ...

class QComboBox(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addItem(self, text: str, userData: Any = None) -> None: ...
    def addItems(self, texts: List[str]) -> None: ...
    def insertItem(self, index: int, text: str, userData: Any = None) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentText(self) -> str: ...
    def currentData(self) -> Any: ...
    def itemText(self, index: int) -> str: ...
    def itemData(self, index: int) -> Any: ...
    def setEditable(self, editable: bool) -> None: ...
    def isEditable(self) -> bool: ...

class QTabWidget(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addTab(self, widget: QWidget, label: str) -> int: ...
    def insertTab(self, index: int, widget: QWidget, label: str) -> int: ...
    def removeTab(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentWidget(self) -> Optional[QWidget]: ...
    def widget(self, index: int) -> Optional[QWidget]: ...
    def setTabText(self, index: int, text: str) -> None: ...
    def tabText(self, index: int) -> str: ...

class QGroupBox(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def setAlignment(self, alignment: int) -> None: ...
    def alignment(self) -> int: ...

class QFrame(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setFrameShape(self, shape: "Shape") -> None: ...
    def frameShape(self) -> "Shape": ...
    def setFrameShadow(self, shadow: "Shadow") -> None: ...
    def frameShadow(self) -> "Shadow": ...
    def setLineWidth(self, width: int) -> None: ...
    def lineWidth(self) -> int: ...

    class Shape:
        NoFrame: int = ...
        Box: int = ...
        Panel: int = ...
        StyledPanel: int = ...
        HLine: int = ...
        VLine: int = ...

    class Shadow:
        Plain: int = ...
        Raised: int = ...
        Sunken: int = ...

class QAbstractScrollArea(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setVerticalScrollBarPolicy(self, policy: Qt.ScrollBarPolicy) -> None: ...
    def verticalScrollBarPolicy(self) -> Qt.ScrollBarPolicy: ...
    def setHorizontalScrollBarPolicy(self, policy: Qt.ScrollBarPolicy) -> None: ...
    def horizontalScrollBarPolicy(self) -> Qt.ScrollBarPolicy: ...
    def setViewport(self, widget: QWidget) -> None: ...
    def viewport(self) -> QWidget: ...

class QAbstractItemView(QAbstractScrollArea):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setSelectionMode(self, mode: "SelectionMode") -> None: ...
    def selectionMode(self) -> "SelectionMode": ...
    def setEditTriggers(self, triggers: "EditTrigger") -> None: ...
    def editTriggers(self) -> "EditTrigger": ...
    def setSelectionBehavior(self, behavior: "SelectionBehavior") -> None: ...
    def selectionBehavior(self) -> "SelectionBehavior": ...
    def clearSelection(self) -> None: ...
    def selectAll(self) -> None: ...

    class SelectionMode:
        SingleSelection: int = ...
        MultiSelection: int = ...
        ExtendedSelection: int = ...
        ContiguousSelection: int = ...
        NoSelection: int = ...

    class EditTrigger:
        NoEditTriggers: int = ...
        CurrentChanged: int = ...
        DoubleClicked: int = ...
        SelectedClicked: int = ...
        EditKeyPressed: int = ...
        AnyKeyPressed: int = ...
        AllEditTriggers: int = ...

    class SelectionBehavior:
        SelectItems: int = ...
        SelectRows: int = ...
        SelectColumns: int = ...

class QListView(QAbstractItemView):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setModel(self, model: Any) -> None: ...
    def model(self) -> Any: ...

class QDockWidget(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def widget(self) -> Optional[QWidget]: ...
    def setFeatures(self, features: "DockWidgetFeature") -> None: ...
    def features(self) -> "DockWidgetFeature": ...
    def setAllowedAreas(self, areas: Qt.DockWidgetArea) -> None: ...
    def allowedAreas(self) -> Qt.DockWidgetArea: ...
    def setFloating(self, floating: bool) -> None: ...
    def isFloating(self) -> bool: ...

    class DockWidgetFeature:
        DockWidgetClosable: int = ...
        DockWidgetMovable: int = ...
        DockWidgetFloatable: int = ...
        DockWidgetVerticalTitleBar: int = ...
        AllDockWidgetFeatures: int = ...
        NoDockWidgetFeatures: int = ...

class QToolBar(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def addAction(self, text: str) -> QAction: ...
    def addAction(self, icon: QIcon, text: str) -> QAction: ...
    def addAction(self, action: QAction) -> None: ...
    def addSeparator(self) -> QAction: ...
    def addWidget(self, widget: QWidget) -> QAction: ...
    def clear(self) -> None: ...

class QStatusBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def showMessage(self, message: str, timeout: int = 0) -> None: ...
    def clearMessage(self) -> None: ...
    def addPermanentWidget(self, widget: QWidget, stretch: int = 0) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...

class QMenuBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addMenu(self, title: str) -> "QMenu": ...
    def addMenu(self, menu: "QMenu") -> QAction: ...
    def clear(self) -> None: ...

class QMenu(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def addAction(self, text: str) -> QAction: ...
    def addAction(self, icon: QIcon, text: str) -> QAction: ...
    def addAction(self, action: QAction) -> None: ...
    def addSeparator(self) -> QAction: ...
    def addMenu(self, title: str) -> "QMenu": ...
    def addMenu(self, menu: "QMenu") -> QAction: ...
    def clear(self) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...

class QSplitter(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(
        self, orientation: Qt.Orientation, parent: Optional[QWidget] = None
    ) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...
    def setOrientation(self, orientation: Qt.Orientation) -> None: ...
    def orientation(self) -> Qt.Orientation: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def setSizes(self, sizes: List[int]) -> None: ...
    def sizes(self) -> List[int]: ...

class QProgressBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def minimum(self) -> int: ...
    def maximum(self) -> int: ...
    def setFormat(self, format: str) -> None: ...
    def format(self) -> str: ...
    def setTextVisible(self, visible: bool) -> None: ...
    def isTextVisible(self) -> bool: ...

class QLCDNumber(QWidget):
    def __init__(
        self, numDigits: int = 5, parent: Optional[QWidget] = None
    ) -> None: ...
    def display(self, value: Union[int, float, str]) -> None: ...
    def setDigitCount(self, nDigits: int) -> None: ...
    def digitCount(self) -> int: ...
    def setSegmentStyle(self, style: "SegmentStyle") -> None: ...
    def segmentStyle(self) -> "SegmentStyle": ...

    class SegmentStyle:
        Outline: int = ...
        Filled: int = ...
        Flat: int = ...

class QScrollArea(QAbstractScrollArea):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def widget(self) -> Optional[QWidget]: ...
    def setWidgetResizable(self, resizable: bool) -> None: ...
    def widgetResizable(self) -> bool: ...

class QAbstractButton(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def click(self) -> None: ...
    def toggle(self) -> None: ...

class QDialogButtonBox(QWidget):
    def __init__(
        self,
        buttons: "StandardButton" = ...,
        orientation: Qt.Orientation = ...,
        parent: Optional[QWidget] = None,
    ) -> None: ...
    def addButton(self, text: str, role: "ButtonRole") -> QPushButton: ...
    def addButton(self, button: QPushButton, role: "ButtonRole") -> None: ...
    def addButton(self, button: "StandardButton") -> QPushButton: ...
    def clear(self) -> None: ...
    def setStandardButtons(self, buttons: "StandardButton") -> None: ...
    def standardButtons(self) -> "StandardButton": ...
    def button(self, which: "StandardButton") -> Optional[QPushButton]: ...
    def clickedButton(self) -> Optional["QAbstractButton"]: ...

    class StandardButton:
        Ok: int = ...
        Open: int = ...
        Save: int = ...
        Cancel: int = ...
        Close: int = ...
        Apply: int = ...
        Reset: int = ...
        Help: int = ...
        SaveAll: int = ...
        Yes: int = ...
        YesToAll: int = ...
        No: int = ...
        NoToAll: int = ...
        Abort: int = ...
        Retry: int = ...
        Ignore: int = ...
        NoButton: int = ...

    class ButtonRole:
        InvalidRole: int = ...
        AcceptRole: int = ...
        RejectRole: int = ...
        DestructiveRole: int = ...
        ActionRole: int = ...
        HelpRole: int = ...
        YesRole: int = ...
        NoRole: int = ...
        ResetRole: int = ...
        ApplyRole: int = ...

class QToolButton(QAbstractButton):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setMenu(self, menu: QMenu) -> None: ...
    def menu(self) -> Optional[QMenu]: ...
    def setPopupMode(self, mode: "ToolButtonPopupMode") -> None: ...
    def popupMode(self) -> "ToolButtonPopupMode": ...
    def setToolButtonStyle(self, style: Qt.ToolButtonStyle) -> None: ...
    def toolButtonStyle(self) -> Qt.ToolButtonStyle: ...

    class ToolButtonPopupMode:
        DelayedPopup: int = ...
        MenuButtonPopup: int = ...
        InstantPopup: int = ...

class QHeaderView(QWidget):
    def __init__(
        self, orientation: Qt.Orientation, parent: Optional[QWidget] = None
    ) -> None: ...
    def setSectionsClickable(self, clickable: bool) -> None: ...
    def sectionsClickable(self) -> bool: ...
    def setSectionsMovable(self, movable: bool) -> None: ...
    def sectionsMovable(self) -> bool: ...
    def setSectionResizeMode(self, mode: "ResizeMode") -> None: ...
    def setSectionResizeMode(self, logicalIndex: int, mode: "ResizeMode") -> None: ...
    def sectionResizeMode(self, logicalIndex: int) -> "ResizeMode": ...
    def setStretchLastSection(self, stretch: bool) -> None: ...
    def stretchLastSection(self) -> bool: ...

    class ResizeMode:
        Interactive: int = ...
        Stretch: int = ...
        Fixed: int = ...
        ResizeToContents: int = ...
