"""
Type stubs for utils.steam_utils
Generated for modorganizer-linux project
"""

from pathlib import Path
from typing import Dict, Optional

class SteamClient:
    def get_steam_path(self) -> Optional[Path]: ...
    def get_installed_games(self) -> Dict[str, Path]: ...
    def get_supported_games(self) -> Dict[str, Path]: ...
    def parse_acf(self, path: Path) -> Dict: ...
